### ISSUE TITLE
no-build-isolation problem

### ISSUE THREAD

**Issue by lolofo** [state-spaces/mamba#104]
Hello,

I'm trying to install the packages.
I encoutered the torch problem you are describing in the README and I used the command

`pip install --no-build-isolation mamba-ssm`

But I still have the same problem. I'm using torch 2.1.2+cu121

And I have the problem : `NameError: name 'bare_metal_version' is not defined`

**Comment by pengzhangzhi** [comment]
you don't have nvcc installed.
