### ISSUE TITLE
Confusion about context saving during training/inference

### ISSUE THREAD

**Issue by Paulkie99** [state-spaces/mamba#113]
Hi, I am hoping to use mamba in a computer vision application. I do not have experience with NLP/autoregressive models so I'm not sure if this may be an obvious question. I would just like to verify my current understanding.

I am experimenting with incorporating the [the Mamba class](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mamba_simple.py) into a larger architecture. Say I pass a batch of dimensions (B, L, D) -- batch size, sequence length, embedding dim to mamba during training. Mamba's output is autoregressive, i.e. output (B, 1, D) takes the hidden state computed from (B, 0, D) into account, right? 

Now, on the next training batch, is the hidden state re-initialised to some initial value, or must I manually "reset" the model? How does this work during inference, if I want to switch inference from one sequence to another, unrelated one? I guess one has to re-initialise the `key_value_memory_dict` in `InferenceParams`?

**Comment by tridao** [comment]
By default the Mamba block is a sequence to sequence map: input has shape (B, L, D), output has shape (B, L, D). Similar to MLP layer or Attention layer. You can use it the same way you'd use an MLP layer or Attention layer.
"def forward(self, hidden_states, inference_params=None):
        """
        hidden_states: (B, L, D)
        Returns: same shape as hidden_states
"

InferenceParams is only for iterative decoding: processing the prompt to store the states (similar to KV cache), then use that to generate token by token. You can check `utils/generation.py` to see how that's done.
