### ISSUE TITLE
Implementation of Discretization B

### ISSUE THREAD

**Issue by YufangMo** [state-spaces/mamba#114]
Dear Gu, I checked your code scan_ref for the implementation of S6. In line 126 I saw you simply use delta*B for the discretization, instead of the ZOH method in your paper. I wonder if there is anything I miss in this code? Or this way (delta*B ) is more useful?

**Comment by albertfgu** [comment]
It makes the implementation slightly simpler without affecting empirical performance. One can think of it as a mix of ZOH for A and Euler discretization for B.

**Comment by YufangMo** [comment]
Thank you  for the answer! Your paper is filled with novelty.
