### ISSUE TITLE
Text Generation fails

### ISSUE THREAD

**Issue by LalchandPandia** [state-spaces/mamba#115]
I am trying to generate using mamba language model. But causal-conv1d gives error. I did pip install.
python 3.9
pytorch=2.0.0 with cuda 11.8
pip install causal-conv1d>=1.1.0
pip install mamba-ssm
mamba-ssm-1.1.1
When I run the code:
python benchmarks/benchmark_generation_mamba_simple.py --model-name "state-spaces/mamba-2.8b" --prompt "My cat wrote all this CUDA code for a new language model and" --topp 0.9 --temperature 0.7

![image](https://github.com/state-spaces/mamba/assets/115443428/98042981-7834-44fc-8923-0f208e7467e3)
![image](https://github.com/state-spaces/mamba/assets/115443428/66f836dc-ab65-4a6b-9523-034fc98309cc)

**Comment by albertfgu** [comment]
What's your triton version?

**Comment by LalchandPandia** [comment]
Triton 2.0.0

**Comment by LalchandPandia** [comment]
The issue can be closed. I resolved it by using updating to torch=2.0.1 using pip. Also, previously I was using conda to install torch.
Installation:  
pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cu118
pip install  causal-conv1d>=1.1.0
pip install --no-cache-dir  mamba-ssm [This installs 1.1.1]

**Comment by LalchandPandia** [comment]
Thanks
