### ISSUE TITLE
Norm Function based on  triton 

### ISSUE THREAD

**Issue by HGao-cv** [state-spaces/mamba#119]
The normalization function in this file 'mamba/mamba_ssm/ops/triton/layernorm.py' cannot run on ubuntu20.04 system. Why is this? Is it necessary to use ubuntu18.04 system?

**Comment by HGao-cv** [comment]
This is the error：subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpuer96k25/main.c', '-O3', '-I/home/miniconda3/envs/vim/lib/python3.10/site-packages/triton/common/../third_party/cuda/include', '-I/home/miniconda3/envs/vim/include/python3.10', '-I/tmp/tmpuer96k25', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpuer96k25/_layer_norm_fwd_1pass_kernel.cpython-310-x86_64-linux-gnu.so', '-L/lib/x86_64-linux-gnu', '-L/lib/i386-linux-gnu', '-L/lib/i386-linux-gnu']' returned non-zero exit status 1.

**Comment by albertfgu** [comment]
We run it fine on Ubuntu 20.04. There's probably an issue with the environment that we can't help debug.
