### ISSUE TITLE
Discrepancy in Discretization of Matrix B: Implementation vs. Paper Details

### ISSUE THREAD

**Issue by Learn2Solve** [state-spaces/mamba#121]
I appreciate the excellent work on this project. I've noticed a discrepancy in the implementation regarding the discretization of matrix B. The paper suggests using formula 4 (attached below) for discretization, but the code seems to use a simple \Delta B.
Could you clarify:

Why this approach was chosen over the one in the paper?
How does this affect the model's performance?

 ![Image 1-22-24 at 3 44 PM](https://github.com/state-spaces/mamba/assets/116197646/02067d9a-a2a0-4b16-8de5-230f3a11c0d3)

**Comment by albertfgu** [comment]
It doesn't affect the model's performance. See other issues for the same question.
