### ISSUE TITLE
Can't import causal_conv1d_cuda

### ISSUE THREAD

**Issue by huansu** [state-spaces/mamba#122]
Hello！
I have installed the causal_conv1d in Windows:
`Building wheels for collected packages: causal_conv1d
  Building wheel for causal_conv1d (setup.py) ... done
  Created wheel for causal_conv1d: filename=causal_conv1d-1.1.1-cp38-cp38-win_amd64.whl size=10107344 sha256=f82d062125db37dcaeb6be1f9e5f84c1b3a2578b54d1f6a4f0c577ad107cbf03
  Stored in directory: c:\users\22318\appdata\local\pip\cache\wheels\aa\5f\89\e04181d3206dac2fadbb6c65b681f67e1c0d33ddbc884febec
Successfully built causal_conv1d
Installing collected packages: argparse, causal_conv1d
  Attempting uninstall: causal_conv1d
    Found existing installation: causal_conv1d 1.1.1
    Uninstalling causal_conv1d-1.1.1:
      Successfully uninstalled causal_conv1d-1.1.1
Successfully installed argparse-1.4.0 causal_conv1d-1.1.1`
But Pycharm give me this:
`ModuleNotFoundError: No module named 'selective_scan_cuda'.`
What should I do to solve this problem?

**Comment by tridao** [comment]
Idk much about compiling for Windows, if you figure out let us know.
