### ISSUE TITLE
d_conv&expand

### ISSUE THREAD

**Issue by gnorZgnoD** [state-spaces/mamba#128]
Hi, author,
  How will d_conv and expand these two paramet  How will d_conv and expand these two parameters affect the performance of Mamba?ers affect the performance of Mamba?

**Comment by tridao** [comment]
d_conv=3 or d_conv=4 didn't seem to make a difference in quality.
`expand` will definitely change the number of parameters, you'd want to control the total number of parameters (e.g. by increasing depth or d_model). `expand=2` seems to work well and easy to match Transformer's number of params (2 Mamba layers having around the same number of params as MHA + MLP).

**Comment by gnorZgnoD** [comment]
tks!

**Comment by petercmh01** [comment]
thanks for the awsome work @tridao would you mind explain (I suggest probably in the readme as well will be helpful for later reference) what `expand` and `d_state` and `d_conv` actually means to the model?

**Comment by albertfgu** [comment]
- `expand` changes the model's width inside the block, this is described in Sec 3.4 of the original Mamba paper (and you can read the Block's code)
- `d_state` is the state expansion factor, you'll have to read the papers for details
- `d_conv` is the convolution kernel width (the causal conv1d inside the block before the main SSM layer)
