### ISSUE TITLE
HELLO, selective_scan

### ISSUE THREAD

**Issue by 812985728** [state-spaces/mamba#131]
DID you have the code of selective_scan_fwd and selective_scan_bwd in python

**Comment by albertfgu** [comment]
HELLO, no we don't

These functions need to be implemented at a lower level for efficiency, but you can check out other reference implementations to understand the model: e.g. https://github.com/johnma2006/mamba-minimal

**Comment by 812985728** [comment]
Thanks very much---- Replied Message ----FromLiu ***@***.***>Date01/30/2024 17:58 ***@***.***> CcTian ***@***.***>***@***.***>SubjectRe: [state-spaces/mamba] HELLO, selective_scan (Issue #131)

DID you have the code of selective_scan_fwd and selective_scan_bwd in python

you may want to refer to this repo: https://github.com/alxndrTL/mamba.py 

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/state-spaces/mamba/issues/131#issuecomment-1916473907",
"url": "https://github.com/state-spaces/mamba/issues/131#issuecomment-1916473907",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
