### ISSUE TITLE
Question regarding Figure 8 Transformer Throughput Baseline

### ISSUE THREAD

**Issue by LeoXinhaoLee** [state-spaces/mamba#136]
Thank you very much for releasing code for this inspiring work! In figure 8 (throughput comparison between Mamba and Transformer) and Appendix E.5 End-to-End Inference, the paper says **a standard Transformer (GPT3 architecture) at 1.3B and 6.7B size. We use the standard Transformer implementation in the Huggingface transformers library.**

However, in the code ```benchmark/benchmark_generation_mamba_simple.py```, it seems like which GPT3 architecture models are used is not specified. Could you please let me know which transformers they are (maybe huggingface links)? Also, do they use Flash Attention? 

Thank you very much for your time and help!

**Comment by tridao** [comment]
I think we were using GPT2 arch (GPT3 has the same arch) but other models of similar size should be around the same. You can try pythia too.

**Comment by LeoXinhaoLee** [comment]
Thank you for your kind reply! We tried Pythia 1.4 and 6.9B, which turned out close to the reported throughput. Thank you very much!
