### ISSUE TITLE
Is there a feature to load an initial state?

### ISSUE THREAD

**Issue by RonanKMcGovern** [state-spaces/mamba#141]
For few-shot prompting, rather than actually putting in that prompt, one could think of just loading a different initial state, correct?

More generally, rather than fine-tuning, perhaps it's enough to load with an initial state corresponding to having prompted with all of that fine-tuning material? i.e. run inference once on the pre-prompt, then save that state?

**Comment by albertfgu** [comment]
Yes, that's correct. We're planning to add that feature relatively soon, but no promises on the exact release date (it's been asked in the GH issues a few times)
