### ISSUE TITLE
Question about exporting Mamba models to GGUF format for Ollama deployment

### ISSUE THREAD

**Issue by zhaohm14** [state-spaces/mamba#142]
I am interested in deploying mamba within the Ollama framework. I was wondering if thers's a way to export Mamba models to GGUF format, or if there are any recommended methods for doing so. 
Thanks a lot!

**Comment by tridao** [comment]
I'm not familiar with the GGUF format but perhaps others might be able to help.

**Comment by supersonictw** [comment]
https://github.com/ollama/ollama/issues/3023

**Comment by zhaohm14** [comment]
> [ollama/ollama#3023](https://github.com/ollama/ollama/issues/3023)

Thanks a lot
