### ISSUE TITLE
Learning rate used for state-spaces/mamba-2.8b-slimpj?

### ISSUE THREAD

**Issue by jzhang38** [state-spaces/mamba#144]
Forgive me if it is already written in the paper somewhere.
I can only find the setup for model up to 1.3B in Table 12.

**Comment by tridao** [comment]
For the 2.8B models we used 3x GPT3 lr I think, so 4.8e-4.

**Comment by radarFudan** [comment]
<img width="911" alt="Screenshot 2024-01-31 at 10 43 35 AM" src="https://github.com/state-spaces/mamba/assets/25528016/7931230c-208f-4e72-9417-8c2b514b8c02">

Question: Just want to double check, the learning rate used for 125M Mamba is 6e-4 or 5 times 6e-4? 

I check the GPT learning rate for 125M size model is 6e-4 and you said that the improved recipe for transformer is five times the peak value.

**Comment by albertfgu** [comment]
it's 5x 6e-4

2.8B is the only one where we lowered the LR to 3x the GPT lr
