### ISSUE TITLE
Set the initial state of SSMs during training (instead of zero tensors)

### ISSUE THREAD

**Issue by jzhang38** [state-spaces/mamba#146]
Thanks for the wonderful work! 
I understand that the current implementation assumes the initial states are just zero tensors.
I can easily manipulate these initial states during inference via the inference param.
Is there a simple way to do this during training?

**Comment by tridao** [comment]
Not for now but we'll release a version that allows changing the initial states soon.

**Comment by CompRhys** [comment]
Can this issue be reopened to track when initial state functionality may become available?
