### ISSUE TITLE
About FFT mentioned in paper

### ISSUE THREAD

**Issue by Sawyer117** [state-spaces/mamba#148]
Hi, I was to understand the paper[https://arxiv.org/pdf/2312.00752.pdf] and reproduce the work. But for section E.5:

E.5 
For convolution, we use the standard implementation in PyTorch, which separately performs FFTs on the inputs
and the filters, multiply them in frequency domain, then performs an inverse FFT to obtain the result. 

above mentioned FFT is used to accelerate computation of convolution. However, in the repo I cannot find any fft related operator or function, and seems the standard implementation of conv1d doesn't include any fft/ifft.
Also when I check the model structure(1.4b), its like this:

MambaLMHeadModel(
  (backbone): MixerModel(
    (embedding): Embedding(50280, 2048)
    (layers): ModuleList(
      (0-47): 48 x Block(
        (mixer): Mamba(
          (in_proj): Linear(in_features=2048, out_features=8192, bias=False)
          **(conv1d): Conv1d(4096, 4096, kernel_size=(4,), stride=(1,), padding=(3,), groups=4096)**
          (act): SiLU()
          (x_proj): Linear(in_features=4096, out_features=160, bias=False)
          (dt_proj): Linear(in_features=128, out_features=4096, bias=True)
          (out_proj): Linear(in_features=4096, out_features=2048, bias=False)
        )
        (norm): RMSNorm()
      )
    )
    (norm_f): RMSNorm()
  )
  (lm_head): Linear(in_features=2048, out_features=50280, bias=False)
)

seems the conv1d with kernel_size=4 theoretically doesn't require a fft to accelerate(or could slow down with fft?)

Maybe I had some misunderstanding somewhere and I really appreciate if anyone could help to clarify on this issue. Thanks.

**Comment by albertfgu** [comment]
The section you are references is benchmarking an alternative to Mamba: global convolution models. These have been popular recently (see Section 2 and Appendix B for many examples). Mamba does *not* use global convolutions or FFT. The details in Appendix E.5 are for the speed benchmark of Mamba's implementation against alternative sequence models.

**Comment by Sawyer117** [comment]
thanks for clarification
