### ISSUE TITLE
Data preparation methods

### ISSUE THREAD

**Issue by RonanKMcGovern** [state-spaces/mamba#155]
I was somewhat surprised to see that Mamba's context length is finite.

I assume this means Mamba was trained on 2k token batches, but resetting the state of "h" in some kind of aggregate way.

Would it be better to feed the value of h at the end of one 2k sequence to be used as the starting value for the next sequence (which would appear in the next batch)?

In principle, this should result in the model being capable of almost infinite length. Or am I misunderstanding something?

**Comment by tridao** [comment]
That'd be interesting to try! Transformer-XL did something similar.

**Comment by radarFudan** [comment]
This stateful approach seems to be common in RNN models (https://arxiv.org/abs/1803.00144).

**Comment by radarFudan** [comment]
For example, the famous LSTM language model by salesforce is using this idea: https://github.com/salesforce/awd-lstm-lm/blob/master/model.py

**Comment by jzhang38** [comment]
I had similar ideas. Unfortunately, mamba currently does not support setting the initial hidden state during training.
https://github.com/state-spaces/mamba/issues/146
CUDA master Tri Dao said it will be implemented soon tho.
I plan to try it ASAP once this functionality is ready.
@RonanKMcGovern or anyone else wanna work together on this? My discord handle is peiyuan007
(btw I have already scaled the mamba fine-tuning length to 16384 and the test PPL keeps going down until ~40K on proof pile. I optimistically we can eventually realize infinite context length.)

**Comment by radarFudan** [comment]
I am also interested in this! I have some slow solution to achieve the setting hidden states during training. (https://github.com/state-spaces/mamba/issues/155)

**Comment by jzhang38** [comment]
Yeah the simplest way is to just substitute selective_scan with a torch implementation, which is what I am currently doing.

**Comment by RonanKMcGovern** [comment]
@jzhang38 that's cool. How much memory did you need to train the 16k context. I tried on an A100 (80 GB) and ran OOM. Did you also train all modules or freeze some?

**Comment by CompRhys** [comment]
+1 for setting the initial state, setting the initial state is likely to be important when using the model in industrial control settings

**Comment by jzhang38** [comment]
https://github.com/jzhang38/LongMamba

**Comment by RonanKMcGovern** [comment]
@jzhang38 that is so good, thanks
