### ISSUE TITLE
Slower training speed?

### ISSUE THREAD

**Issue by xyzhang626** [state-spaces/mamba#156]
Thank the authors for the great work and making it open-sourced.
.
I made a minimal trainable mamba on Tinystories [here](https://github.com/xyzhang626/Mamba-tinystories) based on llama2.c by a few lines.  But found it is ~13% slower in training on my v100s (800ms v.s. 650ms per iter, 2048 seq_len) than `torch.compile`d Transformers. 

Does it work as expected? I also notice the `torch.compile` can not directly work with the current mamba model in this repo. Is that one factor given the mamda has been equipped with serval fused ops.

**Comment by quancs** [comment]
I have the same question, the implementation of `mamba` could not be compiled, and is slower than transformer

**Comment by albertfgu** [comment]
That is expected. It is not compatible with `torch.compile`. And at 2k sequence length it should be slower than a Transformer. At 8k it is faster.

**Comment by xyzhang626** [comment]
thanks @albertfgu for the clarification. 

Mamba has been a super great work.  It would be even nicer if it can be trained faster than transformers. Could you further explain the factors make the training slower on 2k? Would like to contribute if possible.

**Comment by albertfgu** [comment]
I don't think that an explanation here would be able to provide any more context than the paper does :)

**Comment by shim0114** [comment]
I've been reviewing the results presented in the paper and found the discussion around the computational efficiency of Mamba and Attention mechanisms particularly interesting. According to Figure 8 in the paper, it appears that Mamba outperforms traditional Attention in terms of computation speed. However, in my own experiments, I observed that the training with Mamba is slower compared to Attention, which seems contradictory to what is presented in the figure.

Could you please clarify where in the paper the reasons for this potential discrepancy might be discussed? Is there a particular implementation detail or experimental setting that might explain the slower training speeds with Mamba that I might have overlooked?

Thank you for your time and assistance.
