### ISSUE TITLE
OSError: [Errno 122] Disk quota exceeded (when running the exemplar evaluation)

### ISSUE THREAD

**Issue by CSWorker45** [state-spaces/mamba#164]
Thanks for the nice work! I was excited to use Mamba for personal deployment. But when I tested it for generation, something like:
`python benchmarks/benchmark_generation_mamba_simple.py --model-name "state-spaces/mamba-130m" --batch 10` 

I encountered a disk quota exceed error during the generation, and it seems the error is in the triton side. The specific error log is as follow:
<img width="977" alt="截屏2024-02-06 12 53 57" src="https://github.com/state-spaces/mamba/assets/147121382/9abb2b46-89b1-427c-a582-5951d91e5789">

I wonder what is the problem here since I am not familiar with triton :( 

Thanks again for the open-sourced project!

**Comment by tridao** [comment]
You can also ask on the triton github.
Probably you'd want to set `TRITON_CACHE_MANAGER` to a location with disk space: https://github.com/openai/triton/issues/2688#issuecomment-1864023418

**Comment by CSWorker45** [comment]
Thanks! The answer helps to resolve the issue
