### ISSUE TITLE
The issues about the initialization of A

### ISSUE THREAD

**Issue by haohang96** [state-spaces/mamba#167]
Hi, I have some questions about the initialization of **A** ([code link](https://github.com/state-spaces/mamba/blob/009bec5ee37f586844a3fc89c040a9c1a9d8badf/mamba_ssm/modules/mamba_simple.py#L104C1-L108C23)):

<div align="left">
<img src="https://github.com/state-spaces/mamba/assets/30290230/34eeef3b-d5a8-4760-a813-6eb91558f975" alt="1" width="600">
</div>

### Regarding the formulation of **A**, I have two questions:

1. In the [S4](https://arxiv.org/pdf/2111.00396.pdf) and [S6](https://arxiv.org/pdf/2312.00752.pdf) papers, **A** should be an $n \times n$ matrix, where $n$ is the hidden state dimension. However, here it is a $d \times n$ matrix.

2. In the paper on [S4D](https://arxiv.org/pdf/2206.11893.pdf), I cannot find the direct definition of the **S4D-real-initialization** method. I searched globally with the keywords "s4d-real" in the paper and found the following definition:

    ![WX20240207-000619@2x](https://github.com/state-spaces/mamba/assets/30290230/63181115-b05d-4637-ad89-c18e45f40d3f)

    I wonder if this corresponds to the definition of the code provided: `A = repeat(torch.arange(1, self.d_state + 1))`?

    Furthermore, if this indeed corresponds to the definition of **A**, I noticed that in the paper, $A_n$ is represented as a negative value $-(n+1)$, but in the code, it is represented as a positive value $n+1$. I am curious about the reason for this difference.

In fact, after referring to a similar issue (#71), I have resolved the first question. So my main questions pertain to the last one. I would greatly appreciate it if anyone could provide answers. Thank you very much! :)

**Comment by tridao** [comment]
Yes S4D-real `A = repeat(torch.arange(1, self.d_state + 1))` corresponds to A_n = -(n + 1) where n goes from 1 to d_state.
In the code we have A positive, then store log_A, then use -exp(log_A) in the `forward` method.

**Comment by haohang96** [comment]
Thanks for your reply, I got it :)
