### ISSUE TITLE
Question regarding the choice of C being of shape (B, L, N)

### ISSUE THREAD

**Issue by apoorv2904** [state-spaces/mamba#172]
Hi,

Thank for releasing the code and such a well written paper. I had one specific question about the choice of C in Mamba in comparison to S4.

<img width="1360" alt="image" src="https://github.com/state-spaces/mamba/assets/9625495/48c9f0b5-dc9f-4e93-89a9-1486844acc59">

In S4, C was of shape (D, N) where as Mamba chooses it to be (B, L, N) when making the model time-varying for C. From my understanding of the `selective_scan_ref` we are using the same weights for each of the D states. Was this choice to keep the memory usage low similar to discretizing A, B to (B, L, D, N) directly in the kernel?

If yes, did you consider to use a low rank decomposition for C (shape : B,L,D,N)  i.e C = C_r M_r? 
Here C_r and M_r are of shape (B, L, N, r) and (r, D) respectively. The actual multiplication can happen on kernel. Thanks for sharing your thoughts on this.

**Comment by tridao** [comment]
Yes the motivation is to reduce memory and parameters.
I'm not sure we ever experimented with low rank C, could be fun to try :D 
In some sense parameter-tying with C is an instance of low-rank. We tie C across the D dimension, which is equivalent to setting M_r (in your notation) to be [1, 1, ..., 1] (i.e. the matrix to replicate C across the D dimension).

**Comment by apoorv2904** [comment]
Thanks for sharing. Yes, that is what I thought about that interpretation as well. I will take a look at the kernels to play around  and share if its useful. I will close the issue and thank you again for such fast response.
