### ISSUE TITLE
Make Mamba modular at least for tokenization and embedding

### ISSUE THREAD

**Issue by hesingh** [state-spaces/mamba#174]
If you see modular mistral.ai, they have a tokenizer.py. Modular code helps port Transformer apps to Mamba. I want to add new bos and eos for different data types, e.g., audio, image, video, etc.

**Comment by tridao** [comment]
Right now we just use a pretrained tokenizer (from GPT-NeoX) and nn.Embedding. I'm not sure what changes you're suggesting.

**Comment by hesingh** [comment]
See Table 1 in this paper. https://arxiv.org/pdf/2312.14125.pdf. Also see Figure 3.

**Comment by tridao** [comment]
Would you like to contribute? We welcome PRs.

**Comment by hesingh** [comment]
I'd be happy to once I understand the code better.

**Comment by hesingh** [comment]
How do I change Mamba to use pretrained GPT-Neox for text input but use another tokenizer for image or video, another for audio?
