### ISSUE TITLE
CUDA extension resources

### ISSUE THREAD

**Issue by DianCh** [state-spaces/mamba#198]
Hi, thank you for releasing this wonderful repo. I have a slightly tangential question: would you mind recommending some resources on learning how to write a full-blown CUDA extension project like this (the lectures I found online are a bit dispersed in different aspects or touch on the surface-level features)? I'd appreciate some pointers :)

**Comment by tridao** [comment]
I don't have strong opinions on CUDA resources but some folks have given suggestions here: https://www.reddit.com/r/MachineLearning/comments/w52iev/d_what_are_some_good_resources_to_learn_cuda/

I'd recommend looking at [Triton](https://github.com/openai/triton) as well: easier to get going if you're already familiar with Python, and get you thinking about parallel programming (i.e., how to decompose a problem into different pieces). This is one of the main point of GPU programming.

**Comment by DianCh** [comment]
Thank you very much!
