### ISSUE TITLE
What is the speed improvement by using `use_fast_path`?

### ISSUE THREAD

**Issue by chen-yingfa** [state-spaces/mamba#216]
As per title. My understanding of the code is that when `use_fast_path=True`, it uses recomputation from the conv1d input to speed up training. Are there any concrete stats on how much improvement is brought by using `use_fast_path=True`?

I am working on changing this part of the code and such result would be very helpful for me.

Thanks in advance.

**Comment by tridao** [comment]
It's faster by a bit, also more memory efficient. Should be fine to disable that if it's easier to work with the other code path.
