### ISSUE TITLE
undefined symbol: _ZN3c104cuda9SetDeviceEi in import selective_scan_cuda

### ISSUE THREAD

**Issue by AlexiaJM** [state-spaces/mamba#217]
Error:
>   File "/home/mila/j/jolicoea/mamba/mamba_ssm/ops/selective_scan_interface.py", line 16, in <module>
>     import selective_scan_cuda
> ImportError: /home/mila/j/jolicoea/mylibs/lib/python3.10/site-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

I am installing using the wheel https://github.com/state-spaces/mamba/releases/download/v1.2.0.post1/mamba_ssm-1.2.0.post1+cu118torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl

I have cuda 11.8, python 3.10, and the latest developmental torch version.

Same problem occurs with the 1.2.0 version of mamba-ssm.

**Comment by AlexiaJM** [comment]
I also have this error:

torch.__version__  = 2.3.0.dev20240304+cu118

      running bdist_wheel
      Guessing wheel URL:  https://github.com/state-spaces/mamba/releases/download/v1.2.0.post1/mamba_ssm-1.2.0.post1+cu118torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
      error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

**Comment by AlexiaJM** [comment]
Thanks using the dev version you provided fixes problem 1. I still have the ssl error but I can fix it by directly installing from the wheel. Its not important, but I'm just leaving this here in case it happens to someone.

```
pip install causal-conv1d mamba-ssm ## not working, weird bug
pip install https://github.com/Dao-AILab/causal-conv1d/releases/download/v1.2.0.post2/causal_conv1d-1.2.0.post2+cu118torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl # works
pip install https://github.com/state-spaces/mamba/releases/download/v1.2.0.post1/mamba_ssm-1.2.0.post1+cu118torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl # works
```

**Comment by GengGengJiuXi** [comment]
I also have this error:
selective_scan_cuda.cpython-310-aarch64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

torch                     2.2.0+cu11.8             pypi_0    pypi
torchaudio                2.2.0+cu118              pypi_0    pypi
cuda 11.8
and i am Aaarch64

What should I do to fix this error?

**Comment by JuiceCoffe** [comment]
> I also have this error: selective_scan_cuda.cpython-310-aarch64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE
> 
> torch 2.2.0+cu11.8 pypi_0 pypi torchaudio 2.2.0+cu118 pypi_0 pypi cuda 11.8 and i am Aaarch64
> 
> What should I do to fix this error?

I also met the problem,have you solve it?Tell me please

**Comment by zh1727100986** [comment]
import selective_scan_cuda
ImportError: /root/miniconda3/envs/RSCaMa_env/lib/python3.9/site-packages/selective_scan_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
python3.9 
torch==2.0.1+cu11.8 torchvision==0.15.2 torchaudio==2.0.2
Can anyone help me? Thank you.

**Comment by Fly-Cat-0** [comment]
https://blog.csdn.net/weixin_52153243/article/details/142737403
I have solved this problem by this link method！！！

**Comment by 9527MY** [comment]
i solve this problem.
at cuda 12.4
pytorch 2.4
python 3.11
i intalled that 
mamba_ssm-2.2.2+cu122torch2.4cxx11abiFALSE-cp311-cp311-linux_x86_64.whl
causal_conv1d-1.4.0+cu122torch2.4cxx11abiFALSE-cp311-cp311-linux_x86_64.whl
you can find at 
https://github.com/Dao-AILab/causal-conv1d/releases/tag/v1.4.0
https://github.com/state-spaces/mamba/releases/tag/v2.2.2

**Comment by leeqiaogithub** [comment]
I had the same problem.

cuda12.1,  pytorch2.4.1+cu121,  python3.10.18
causal_conv1d-1.5.0.post8+cu12torch2.4cxx11abiTRUE-cp310-cp310-linux_x86_64.whl
mamba_ssm-2.2.0+cu122torch2.4cxx11abiTRUE-cp310-cp310-linux_x86_64.whl

Any suggestions would be very helpful.

**Comment by shuyi-zhang-1996** [comment]
若安装错误提示undefined symbol: _ZNSt7__cxx11... → ABI不匹配
解决方案：卸载当前包，安装另一个ABI版本
# 必须确保与PyTorch的ABI一致！
import torch
if torch._C._GLIBCXX_USE_CXX11_ABI:
    print("安装 cxx11abiTRUE 版本")
else:
    print("安装 cxx11abiFALSE 版本")

**Comment by WeiXvanZhou** [comment]
@shuyi-zhang-1996 Thank you so much! Your advice is very helpful !!!

**Comment by Zjj021127** [comment]
you can use this code to find out which version you should download
`import torch
if torch._C._GLIBCXX_USE_CXX11_ABI:
       print("please download cxx11abiTRUE version")
else:
       print("please download cxx11abiFALSE version")
`
then，go to [https://github.com/state-spaces/mamba/releases](url) to chose the mamba you need.you can download the correct version according to your torch,cuda and python.

**Comment by LiulianC** [comment]
<html>
<body>
<hr>
<h3>🐛 Issue: Build and Import Errors with <code inline="">mamba-ssm</code> + <code inline="">causal-conv1d</code> on PyTorch 2.6 / CUDA 12.4</h3>
<p>Hi, thank you very much for your great work on <strong>Mamba</strong> and <strong>Causal-Conv1D</strong>!<br>
I’m trying to build and run the latest version on my environment, but keep encountering consistent import/runtime errors even after multiple installation attempts.<br>
I’d really appreciate your guidance or suggestions on how to fix it 🙏</p>
<hr>
<h3>🧩 Environment</h3>

Component | Version
-- | --
Python | 3.10
PyTorch | 2.6.0+cu124
CUDA | 12.4
ABI | abi=FALSE (correct build)
OS | Linux (x86_64)


<hr>
<h3>📦 Installation Attempts</h3>
<p>I have tried multiple installation methods:</p>
<ol>
<li>
<p>Using prebuilt wheels:</p>
<pre><code class="language-bash">pip install mamba-ssm==2.2.6.post3
pip install causal-conv1d==1.5.3.post2
</code></pre>
</li>
<li>
<p>Building from source:</p>
<pre><code class="language-bash">pip install -e ./causal-conv1d-1.5.0.post5 --no-build-isolation
pip install -e ./mamba-ssm-2.2.3 --no-build-isolation
</code></pre>
<p>and also tried versions:</p>
<ul>
<li>
<p><code inline="">mamba-ssm==2.2.3</code>, <code inline="">2.2.6</code></p>
</li>
<li>
<p><code inline="">causal-conv1d==1.5.0.post5</code>, <code inline="">1.5.3.post1</code></p>
</li>
</ul>
</li>
</ol>
<p>Unfortunately, the same issues persist across all of them.</p>
<hr>
<h3>⚠️ Error Logs</h3>
<p><strong>1️⃣ Import Error</strong></p>
<pre><code class="language-python">File "/home/gzm/cp310pt26/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 20, in &lt;module&gt;
    import selective_scan_cuda
ImportError: /home/gzm/cp310pt26/lib/python3.10/site-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEab
</code></pre>
<hr>
<p><strong>2️⃣ Runtime Error</strong></p>
<pre><code class="language-python">File "/home/gzm/Mamba/mamba_ssm/ops/triton/ssd_combined.py", line 799, in forward
    causal_conv1d_fwd_function(...)
TypeError: 'NoneType' object is not callable
</code></pre>
<hr>
<p><strong>3️⃣ Function Signature Mismatch</strong></p>
<pre><code class="language-python">File "/home/gzm/cp310pt26/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 779, in forward
    causal_conv1d_cuda.causal_conv1d_fwd(...)
TypeError: causal_conv1d_fwd(): incompatible function arguments.
</code></pre>
<hr>
<h3>🔍 Additional Notes</h3>
<ul>
<li>
<p>The <strong>first and second errors</strong> seem related — if I modify the try/except in the import logic (forcing <code inline="">causal-conv1d-cuda</code> import), they switch places or disappear, suggesting it’s the <strong>same shared library import issue</strong>.</p>
</li>
<li>
<p>I ensured that PyTorch and CUDA versions match (<code inline="">torch.version.cuda == "12.4"</code>) and that the ABI setting is <code inline="">False</code>.</p>
</li>
<li>
<p>The same behavior occurs with both <code inline="">.whl</code> installation and source builds (<code inline="">--no-build-isolation</code>).</p>
</li>
</ul>
<hr>
<h3>🙏 Question</h3>
<p>Could you please advise what might cause this symbol / import mismatch issue?<br>
Is there a specific <code inline="">mamba-ssm</code> ↔ <code inline="">causal-conv1d</code> version pair recommended for PyTorch 2.6 + CUDA 12.4?<br>
Any hints on how to rebuild the CUDA extensions correctly would be really appreciated.</p>
<p>Thank you very much for your time and amazing work! ❤️</p>
<p>Best regards,<br>
<hr>
</body></html>
</body>
</html>
