### ISSUE TITLE
AttributeError: module 'triton.language' has no attribute 'math'

### ISSUE THREAD

**Issue by Lily-Le** [state-spaces/mamba#219]
AttributeError: module 'triton.language' has no attribute 'math'
[selective_state_update.py](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/ops/triton/selective_state_update.py) line 78
```python  
    if HAS_DT_BIAS:
        dt += tl.load(dt_bias_ptrs, mask=offs_m < dim, other=0.0).to(tl.float32)
    if DT_SOFTPLUS:
        dt = tl.where(dt <= 20.0, tl.math.log1p(tl.exp(dt)), dt)
```

I'm using torch 2.0.1 and triton 2.0.0.  What's the expected version of triton? I didn't find triton.language.math.log1p in triton 2.1.0 either. Thanks for the brilliant work.

**Comment by tridao** [comment]
triton 2.1.0 has it
```
In [4]: triton.__version__
Out[4]: '2.1.0'

In [5]: triton.language.math.log1p
Out[5]: <function triton.language.math.log1p(arg0, _builder=None)>
```

**Comment by Lily-Le** [comment]
Sorry for the mistake. I simply searched the log1p func in triton repository as my current driver version doesn't support  higher version of torch and triton.   It would be great if you could update the environmental requirements in the README document. Thanks!

**Comment by Akutto** [comment]
The code tl.math.log1p(tl.exp(dt)) should be updated to , softplus(dt)aligning with the latest source code implementation.
