### ISSUE TITLE
Can non-linear ssm(data-dependent input) utilize Mamba's parallelism acceleration？

### ISSUE THREAD

**Issue by EricLina** [state-spaces/mamba#220]
Thanks for your excellent work! I have a question regarding parallelism in non-linear recursive form. 

For parallelism in recursive form, is it necessary for each time step's input to be independent? That is to say: if the input at time step t, x[t], is defined as f (x[0~t]), where f is a nonlinear function, can it still be parallelized?

I noticed that the parallel operations in SSM (State Space Model) actually follow the linear RNN form, and the inputs to SSM are already determined. However, in certain scenarios (such as online settings), the inputs for future time steps are uncertain. In such cases, can we still use Mamba's SSM for parallelism acceleration? If not, are there any alternative solutions?

**Comment by tridao** [comment]
Probably will be hard for such a general function. E.g. it was hard to parallelize nonlinear RNNs such as LSTM.
