### ISSUE TITLE
What's the difference between Mamba and MambaLMHeadModel?

### ISSUE THREAD

**Issue by renyuanzhe** [state-spaces/mamba#222]
If I have an input of [batchsize,length,dim], how can I use the model

**Comment by zigzagcai** [comment]
[Mamba ](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mamba_simple.py#L31-L294) can be used to construct one layer of mamba block.
[MambaLMHeadModel](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/models/mixer_seq_simple.py#L176-L265) is a reference implementation of mamba model, which consists of dozens of layers mamba block, and also the embedding layers, output layers.

**Comment by renyuanzhe** [comment]
> From my understanding, [Mamba ](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mamba_simple.py#L31-L294) can be used to construct one layer of mamba block. [MambaLMHeadModel](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/models/mixer_seq_simple.py#L176-L265) is a reference implementation of mamba model, which consists of dozens of layers mamba block, and also the embedding layers, output layers.
> 
> If I have an input of [batchsize,length,dim], you can pass it into the [Mamba ](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mamba_simple.py#L31-L294) block

thank you
