### ISSUE TITLE
Issue with Initializing Non-zero Hidden State in `InclusiveScan` Kernel

### ISSUE THREAD

**Issue by haonan3** [state-spaces/mamba#228]
Hello,

I've encountered a challenge while working with `InclusiveScan` related to initializing a non-zero hidden state. The computation of `InclusiveScan` utilizes `thread_data` as shown below:

```cpp
SSMScanPrefixCallbackOp<weight_t> prefix_op(running_prefix);
Ktraits::BlockScanT(smem_scan).InclusiveScan(
    thread_data, thread_data, SSMScanOp<weight_t>(), prefix_op
);
```

In the current implementation, the hidden state is implicitly initialized to zero. Consequently, the update equation `x = a[i] * x + b[i]` leads to initial values `x0 = b0; x1 = a1 * b0 + b1`.

However, I'm aiming to introduce a non-zero initial hidden state `x`. My approach was to adjust the initial value of `thread_data` for `r=0` as follows:

```cpp
if (r == 0) {
    thread_data[i] = make_float2(exp2f(delta_vals[r][i] * A_val[r]), 
                                 exp2f(delta_vals[r][i] * A_val[r]) * x[i].x + 
                                 !kIsVariableB ? delta_u_vals[r][i] : B_vals[i] * delta_u_vals[r][i]);
} else {
    thread_data[i] = make_float2(exp2f(delta_vals[r][i] * A_val[r]),
                                 !kIsVariableB ? delta_u_vals[r][i] : B_vals[i] * delta_u_vals[r][i]);
}
```

Despite these adjustments, my results do not align with those obtained from equivalent PyTorch code. I suspect the direct usage of `x[i].x` may be incorrect for initializing the hidden state. 

Could someone provide insights on the correct approach to initialize and compute the non-zero hidden state within `InclusiveScan`? Any guidance or suggestions to align my CUDA implementation with the PyTorch results would be highly appreciated.

**Comment by tridao** [comment]
Hard to say what's wrong, you can print things out to debug:
```
if (blockIdx.x == 0 && blockIdx.y == 0 && threadIdx.x == 0) {
    printf("i = %d, x[i].x = %f\n", i, x[i].x);
}
```
