### ISSUE TITLE
Reason for `bias=False` hardcoded in `x_proj`

### ISSUE THREAD

**Issue by haileyschoelkopf** [state-spaces/mamba#231]
Hi! Thanks very much for the very clear paper and code release.

I have one question regarding the biases on the various linear projections in the Mamba block code--

https://github.com/state-spaces/mamba/blob/34076d664838588a3c97727b263478ab9f621a07/mamba_ssm/modules/mamba_simple.py#L77-L79

I understand why we want to always hardcode a bias in `dt_proj` but I couldn't think of a reason that it is impossible to have a bias in `x_proj`. However, it appears that `MambaInnerFn` does not allow a bias for x_proj to be passed, so it seems like a bias here is intentionally unsupported. 

Is there something I've overlooked here, or is this a decision that was made based on some preliminary ablations, etc.?

Thank you!

**Comment by tridao** [comment]
Generally we prefer to not have bias in Linear layers (e.g. following PaLM, LLaMa). dt_proj needs a bias since we want softplus(dt) to fall within some range (e.g. 1e-4 to 1e-1). 
I don't think we did an ablation with x_proj bias but I don't expect having a bias to help or hurt.

**Comment by haileyschoelkopf** [comment]
Thanks for the quick response! makes sense : )

**Comment by ken012git** [comment]
Hi, I have a follow up question about `dt_proj.bias`: I am curious about the reason behind not adding bias with the dt_proj linear function here, but push the addition to cuda/triton kernel instead:
https://github.com/state-spaces/mamba/blob/34076d664838588a3c97727b263478ab9f621a07/mamba_ssm/modules/mamba_simple.py#L232-L235

> Generally we prefer to not have bias in Linear layers (e.g. following PaLM, LLaMa). dt_proj needs a bias since we want softplus(dt) to fall within some range (e.g. 1e-4 to 1e-1). I don't think we did an ablation with x_proj bias but I don't expect having a bias to help or hurt.

**Comment by tridao** [comment]
For speed reason, though it's probably very minor now that pytorch's F.linear can fuse matmul and bias into 1 kernel.

**Comment by jinlovespho** [comment]
Hi, another follow up question

https://github.com/state-spaces/mamba/blob/3b0dde5a20659073af5684e966a81981e614789e/mamba_ssm/modules/mamba_simple.py#L134C9-L141C82

**Comment by jinlovespho** [comment]
Hi, I just have another question that is most similar to this issue, so I'll just ask here :)

I've looked through the issues but couldn't find a reason to manually calculate the input projection. 

https://github.com/state-spaces/mamba/blob/3b0dde5a20659073af5684e966a81981e614789e/mamba_ssm/modules/mamba_simple.py#L134C9-L141C82

Why not just do, xz = self.in_proj(hidden_states) ?

**Comment by tridao** [comment]
As mentioned in the comment, bc `We do matmul and transpose BLH -> HBL at the same time`
