### ISSUE TITLE
 No module named 'selective_scan_cuda'

### ISSUE THREAD

**Issue by kabbas570** [state-spaces/mamba#237]
Hello, thanks for the nice work.
Getting the following error at line 16: https://github.com/state-spaces/mamba/blob/main/mamba_ssm/ops/selective_scan_interface.py#L42
Tried to look here, https://github.com/state-spaces/mamba/tree/main/csrc/selective_scan
, but we cannot see any module/file with a name, 'selective_scan_cuda'

Thanks 
Cheers
Abbas

**Comment by radarFudan** [comment]
I am not very familiar but I once found the relevant code in 
https://github.com/state-spaces/mamba/blob/9127d1f47f367f5c9cc49c73ad73557089d02cb8/csrc/selective_scan/selective_scan.cpp#L59
and 
https://github.com/state-spaces/mamba/blob/9127d1f47f367f5c9cc49c73ad73557089d02cb8/csrc/selective_scan/selective_scan_fwd_kernel.cuh#L333

**Comment by tridao** [comment]
If you follow the installation instruction it should install the CUDA extension `selective_scan_cuda`.

**Comment by kabbas570** [comment]
Before you install Mamba, we need to load the Cuda version of 11.8.0. However, before that, please make sure that the PyTorch we have is also installed using the same Cuda version of 11.8.0.
The Cuda version of 11.8.0, in my case, may be different, as suggested by the repo owner.
