### ISSUE TITLE
optimal alphabet size for tokenization?

### ISSUE THREAD

**Issue by hrbigelow** [state-spaces/mamba#25]
PS - is there a discord or discuss channel where this would be more appropriate?

In your paper you seem to use the same tokenizer (and hence alphabet size I assume) to compare Mamba models to Transformers.  But, I wondered if you'd thought about implications of smaller or larger alphabet sizes?

Intuitively it seems like, given Mamba's ability to handler longer context, there is the possibility for a smaller alphabet.  Obviously this is a tradeoff and slows down inference but I wondered if it would provide a win in perplexity and generalization.

**Comment by albertfgu** [comment]
Great question! We have not tried anything along these lines, but I think it would be a great idea to try Mamba on finer-grained data (perhaps char-level modeling?) that requires longer context, and see how it compares to Transformers. There's a lot of unknowns about these new models!

**Comment by hrbigelow** [comment]
Oh cool, good to hear that.  Thank you!

**Comment by junphine** [comment]
I use char-level wikitext-103 tokens to train mamba, It seems to produce smooth sentences.  But in a very long step, loss approaches 1.66 and then nan occurs

**Comment by skyler14** [comment]
> I use char-level wikitext-103 tokens to train mamba, It seems to produce smooth sentences. But in a very long step, loss approaches 1.66 and then nan occurs

any writeups or further results you came across from char level embedding?
