### ISSUE TITLE
Increasing the channels via SSM block 

### ISSUE THREAD

**Issue by kabbas570** [state-spaces/mamba#252]
Hello, thanks for the nice work. I would like to know if I can double the number of channels, like here. I want the y to have the shape of [ 2,64,32] instead of [ 2,64,16].

```import torch
from mamba_ssm import Mamba

batch, length, dim = 2, 64, 16
x = torch.randn(batch, length, dim).to("cuda")
model = Mamba(
    # This module uses roughly 3 * expand * d_model^2 parameters
    d_model=dim, # Model dimension d_model
    d_state=16,  # SSM state expansion factor
    d_conv=4,    # Local convolution width
    expand=2,    # Block expansion factor
).to("cuda")
y = model(x)```

**Comment by tridao** [comment]
That should work. Did you try?

**Comment by kabbas570** [comment]
@tridao, thanks for the quick reply. I tried this, and it produced the same size output as input.
x shape --> torch.Size([2, 64, 16])
y shape --> torch.Size([2, 64, 16])

**Comment by tridao** [comment]
Oh I see. You can change the `out_proj` module within the Mamba layer to increase output dimension.

**Comment by kabbas570** [comment]
@tridao thanks for directing to it, changing this line it worked. 

https://github.com/state-spaces/mamba/blob/9127d1f47f367f5c9cc49c73ad73557089d02cb8/mamba_ssm/modules/mamba_simple.py#L117
