### ISSUE TITLE
About S6 Selection Mechanism and Induction Heads Task

### ISSUE THREAD

**Issue by gyu-heo** [state-spaces/mamba#272]
Thank you for developing this beautiful architecture; it has greatly inspired our research.

I am curious about how a Mamba block can be efficient in induction heads tests, which is somewhat related to the previously closed issue #31. I find it hard to believe that a single S6 block can be efficient in this context. Consider the following task structure:

**_A 3 B 2 C 8 D 4 ... (avalanche of tokens) ... A -> 3_**

The core idea is that the selection mechanism can regulate the integration window and almost disregard irrelevant inputs. However, in such tasks, a token like A becomes crucial only at the very end. Before the last token, model does not know which token is the task-relevant token, Therefore, a single S6 layer might struggle to control the $\Delta$ value, especially in a recurrent mode.

Yet, Mamba performs exceptionally well in induction head tasks, suggesting that a two-layer S6 structure might be effective. Could it be that the first S6 layer forms an intermediate nonlinear kernel, enabling the second layer to manage its $\Delta$ effectively, even when it's theoretically uncertain which token is significant until the task's conclusion?

Alternatively, does considering induction heads in a recurrent setting not make sense? Is $\Delta$ at $t = n$ not a function of an input at $t = n$, but a function of the entire input data?  If so, it suggests that in recurrent mode, Mamba possesses a "prophet" feature that informs the main SSM of the appropriate discretization window. Given this, would Mamba still excel in induction head tasks in recurrent mode?

Appreciate your consideration!

**Comment by tridao** [comment]
For sequences that are not too long, the model can commit to memory the mapping A -> 3, B -> 2, C -> 8 etc, then recall at the end.
Ofc for sequences that are super long and there's no pattern in the mapping, it would have more information than what the model can store in the states (depending on state dimension, number of layers) and it won't work.

**Comment by gyu-heo** [comment]
I see. If I've understood correctly, the model might learn to ignore token pairs it has already seen, performing well as long as the task doesn't exceed the maximum information capacity of a single S6 block (depends on state size). Does this suggest that a single S6 block has the potential to handle induction head tasks of a reasonable size effectively?
