### ISSUE TITLE
Compared to self-attention, does Mamba not need multiple heads per layer?  Or positional embeddings?

### ISSUE THREAD

**Issue by hrbigelow** [state-spaces/mamba#29]
Hi,

Looking through the [MambaLMHeadModel](https://github.com/state-spaces/mamba/blob/0131c1e94a46fc9f70bcfc9d57962963bb2f0b9e/mamba_ssm/models/mixer_seq_simple.py#L173) I don't see any corresponding notion of the 'head' that exists with MultiHead Attention.  I'm curious what is the status of this in the Mamba world?

In MHA, I remember the [transformer circuits blog article](https://transformer-circuits.pub/2021/framework/index.html) explained that each head reads its keys and queries from a particular lower-dimensional subspace (mediated by W_k and W_q) of the previous output representation, and writes to a particular subspace (mediated by W_v).

Also, I didn't see any mention in the paper or the code of the use of positional embeddings - is this notion obsolete?  At least with transformers, it seems that positional embeddings are essential for the lower head in the Induction Heads to be able to move information forward by one position in a content-agnostic way.  How does Mamba achieve this if it doesn't use positional  embeddings?  Or, does it use a different mechanism to solve the in-context learning task?

Best,

Henry

**Comment by tridao** [comment]
1. We just apply the selective SSM to each channel / hidden dimension separately, there's no concept of "head". In this sense it's similar to depthwise convolution. The in projection and output projections mixes the channels.
2. There's no explicit position embedding. The model operates in a recurrent way:
hidden_state at time t+1 = function of hidden_state at time t and input at time t + 1.
In this sense it's similar to RNNs (e.g. LSTM). The model does have information on which input token comes first, which input token comes right after, etc.

Re: in-context learning: we actually don't know exactly the mechanism the model is using, all this stuff is new and there are lots to explore. One can hypothesize that as the model processes the prompt, it updates its hidden states to store important information, then use that to generate responses.

Transformer circuits describe 1 way transformers can do ICL. A very interesting question is whether other architectures also do ICL that way, or if there's another path.

**Comment by hrbigelow** [comment]
Great, thank you Tri for the clarification.  Very nice to not need positional embedding or individual heads.

**Comment by hrbigelow** [comment]
> Re: in-context learning: we actually don't know exactly the mechanism the model is using, all this stuff is new and there are lots to explore. One can hypothesize that as the model processes the prompt, it updates its hidden states to store important information, then use that to generate responses.

> Transformer circuits describe 1 way transformers can do ICL. A very interesting question is whether other architectures also do ICL that way, or if there's another path.

My sense is *in-context learning* as a concept is at least aspirationally meant to refer to the ability of the model to complete a pattern A B .... A -> B, where A and B are not just tokens, but short token strings.  In this setting, 'perfect generalization' would mean successfully predicting B when both A and B strings were never seen before in the training data.  In such a setting one can argue from first principles there is no other way to solve this but the model learns to copy the information B from context to output.

In your paper the induction head task was of course much easier than this - a 16 token alphabet, and you are only trying to recall a single token, none of which are novel during testing.  (Although the context as a whole is novel)  It would be interesting to hit Mamba with the more challenging induction head task.
