### ISSUE TITLE
How can I know what the variables in the code refer to?

### ISSUE THREAD

**Issue by Liyuansongdsb** [state-spaces/mamba#290]
I studied the paper of mamba and got this code. but I still do not know how to implement it. 
Because I cannot understand what mean the variable in the code refers to, just like "d_model", "expand"....
How should I learn this code? Should I learn the code of H3 or SSM?
Hope to get your help.

**Comment by ramzan-basheer** [comment]
@Liyuansongdsb usually such models encode the input from its original dimension to an encoding space with certain dimension of your choice. The d_model refers to the dimension of that encoding space. if your input is of shape (B,L,D) then the encoder encodes into (B,L, d_model)
Mamba block expands the input into 2 originally. Hence expand=2.
