### ISSUE TITLE
The origin of the name mamba?

### ISSUE THREAD

**Issue by 354246695** [state-spaces/mamba#293]
Your work is excellent!
I would like to raise a non-technical question: What is the origin of the name mamba for this model?
(Because I am a basketball enthusiast, my first reaction to this name was NBA superstar Kobe Bryant, so I am very curious if there is any connection between them. Finally, regardless of whether I answer or not, thank you again for your work!)

**Comment by albertfgu** [comment]
It's explained in the original Twitter thread! https://twitter.com/_albertgu/status/1731727672286294400
