### ISSUE TITLE
Problems installing the packages

### ISSUE THREAD

**Issue by WilliamHoo** [state-spaces/mamba#30]
I am using an aws ec2 instance

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04

When i tried to run the command
`pip install causal-conv1d` i got an error message saying a module called 'packaging' is missing. 

the entire error message can be found below:
<img width="668" alt="Screenshot 2023-12-07 at 1 51 49 PM" src="https://github.com/state-spaces/mamba/assets/21349011/f9bcfdd3-c8fb-4b54-bba9-3c8d72b921bd">

Then i tried to install from the repository, but have the same error.

**Comment by pjsample** [comment]
`pip install packaging`

**Comment by WilliamHoo** [comment]
thanks!
