### ISSUE TITLE
About test_mamba_inner_fn.

### ISSUE THREAD

**Issue by kuiran** [state-spaces/mamba#301]
I modify some code in selective_scan_cuda and using the test_selective_scan.py to test.  The test_selective_scan results is correct, but the results of test_mamba_inner_fn is wrong, I test the test_mamba_inner_fn with  the unmodified selective_scan_cuda and the results are still incorrect. I would like to know how to determine if the results of test_mamba_inner_fn are correct. I really hope to get your help. Thanks.

**Comment by tridao** [comment]
Sorry we don't have cycles to debug, but the test is testing against the reference implementation `mamba_inner_ref`. You can take a look at that function (it's in Pytorch).

**Comment by kuiran** [comment]
Thanks
