### ISSUE TITLE
revise the selective_scan_cuda

### ISSUE THREAD

**Issue by Sunzechen1219** [state-spaces/mamba#304]
Hello！I want to change this function, but it looks like it's encapsulated by cuda_c, how do I change it?

**Comment by tridao** [comment]
You can change the CUDA code in `csrc`

**Comment by EddieEduardo** [comment]
> You can change the CUDA code in `csrc`

Could you specify which script in scrc needs to be modified, for example, if I want to revise selective_scan_cuda.fwd, which script and which part should I revise?

Thanks for replying.
