### ISSUE TITLE
how i use mamba just like Transformer in my work?

### ISSUE THREAD

**Issue by CharlieHon** [state-spaces/mamba#305]
Thanks for your excellent work! I' m learning Mamba now, but it seems that the apis provided are specially for nlp use, like the parameter vocab_size etc. And i really hope to use Mamba block in my work just like Transformer, but the code is too complex for me(cry). Should i change the [class MambaConfig:](url) and create a custom class like [class MambaLMHeadModel(nn.Module, GenerationMixin):](url)? I would greatly appreciate it if anyone could provide assistance or relevant work examples!

**Comment by poult-lab** [comment]
I think we have to refer S4 or Vim or VMamba if we want to have classification tasks.

**Comment by CharlieHon** [comment]
@poult-lab Thanks for your advice. I have developed my model based on VMamba, and it operates as I intended. However, it is indeed a challenging task to fine-tune the model parameters for optimal performance in my work.

**Comment by poult-lab** [comment]
@CharlieHon I also developed the Vim to my work, but I am countering the very series problem of overfitting.
