### ISSUE TITLE
What is the reasoning behind adding causal_conv +silu before SSM?

### ISSUE THREAD

**Issue by yxchng** [state-spaces/mamba#307]
I try 2 variants: remove causal conv and remove both causal conv and silu, and they both seem to destabilize training and give me NaN. Is it normal?

**Comment by Hprairie** [comment]
@tridao I am curious if you had a reason for why it can work fine without the conv. From my understanding without the conv there would be no feature mixing in embedding space other than the final language modelling head? Thanks for the fantastic codebase and paper!

**Comment by Hprairie** [comment]
Ahh nvm, I see that they could also come into play through the projection of B, C, and delta. However, when you say worse quality do you mean just worse benchmark performance?

**Comment by tridao** [comment]
Yes, worse validation loss without the conv1d.
