### ISSUE TITLE
Are there plans to release mamba for torch 2.3?

### ISSUE THREAD

**Issue by s-rog** [state-spaces/mamba#316]
Hello, currently I can get mamba working on 2.2 but that breaks flash-attn, which works on 2.3 but breaks on 2.2.

Both have the same error of unrecognized symbol importing XXX_cuda on import.
I also tried building from source but still get the same symbol error (which I thought was strange).

Would just like to ask before I refactor my env again. Thanks for your amazing works.

**Comment by tridao** [comment]
v1.2.1 now includes wheels for pytorch 2.3.
