### ISSUE TITLE
ImportError: selective_scan_cuda is installed, but still problem...

### ISSUE THREAD

**Issue by JayNine25** [state-spaces/mamba#318]
/data/anaconda3/condabin/conda run -n py312 --no-capture-output python /tmp/pycharm_project_536/mamba_ssm/training/pretrain.py 
Traceback (most recent call last):
  File "/tmp/pycharm_project_536/mamba_ssm/training/pretrain.py", line 4, in <module>
    from mamba_ssm.models.mixer_seq_simple import MambaLMHeadModel
  File "/tmp/pycharm_project_536/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/tmp/pycharm_project_536/mamba_ssm/ops/selective_scan_interface.py", line 16, in <module>
    import selective_scan_cuda
**ImportError: /data/anaconda3/envs/py312/lib/python3.12/site-packages/selective_scan_cuda.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi**
ERROR conda.cli.main_run:execute(124): `conda run python /tmp/pycharm_project_536/mamba_ssm/training/pretrain.py` failed. (See above for error)

**Comment by jeremy110** [comment]
Maybe check your cuda version is right?

**Comment by JayNine25** [comment]
> Maybe check your cuda version is right?

Did you mean if my cuda version matches Pytorch? I believe they do match because I created a new virtual environment for mamba and checked cuda version before installing Pytorch.

And I installed mamba-ssm from source with `pip install .` from this repository. So it is automatic; it should match my cuda version too.

I also tried install by wheel files, but it said everything is already installed.

**Comment by JayNine25** [comment]
I have pass `--force-reinstall` to pip to reinstall the wheel file, but still can't import selective_scan_cuda. And I notice that PyCharm IDE warn me No module named 'selective_scan_cuda' . However, the reinstalling has succeeded.

**Comment by JayNine25** [comment]
I solved this issue finally. If you have the same problem, you can follow this (You should change cuda version to match your machine and change gcc_linux-64 version to match your cuda version.  Anything else shouldn't be changed):

`conda create -n myenv python=3.12
conda activate myenv
conda install cudatoolkit=11.8 -c conda-forge
conda install pytorch=2.2 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
conda install cuda-nvcc=11.8 -c nvidia
conda install packaging -c conda-forge
conda install -c conda-forge gcc_linux-64=11 gxx_linux-64=11
pip install causal-conv1d>=1.2.0
MAMBA_FORCE_BUILD=TRUE pip install mamba_ssm
`

The crucial part is that 

1. **DO NOT use PyTorch version later than 2.2 (version 2.3 caused the problem of _ZN3c104cuda9SetDeviceEi )**
2. DO NOT --force-reinstall wheel files, it will install CUDA 12.1 which mismatch my machine even the wheel file has "cu118"
3. The "cxx11abiTRUE" version of the wheel files may cause problems, but I succeed by 'MAMBA_FORCE_BUILD=TRUE pip install mamba_ssm', so I did't determine is it that caused problem,   which is _ZN3c107WarningC1ESt7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEERKNS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb.
