### ISSUE TITLE
How to handle the long sequence data (one-dimension; 10000 steps) via Mamba

### ISSUE THREAD

**Issue by poult-lab** [state-spaces/mamba#321]
Perhaps I overlooked some details in the paper. I'm curious about how to apply Mamba to a one-dimensional dataset. As far as I understand, Mamba is based on the S4 architecture, which is known for handling long sequence datasets. Considering the largest model dimension is 2560, if I have a sequence dataset with 8000 steps, how should I structure the data for Mamba? Would it be necessary to incorporate a CNN or linear layer for preprocessing?

**Comment by tridao** [comment]
Mamba is a sequence-to-sequence layer. You can use it in a similar way that you would use an attention layer.

**Comment by poult-lab** [comment]
Okay, thank you for your prompt response. I will close this issue.
