### ISSUE TITLE
What should I do？Critical libmamba [json.exception.type_error.302] type must be string, but is null

### ISSUE THREAD

**Issue by helloworldABCD1234** [state-spaces/mamba#322]
command:mamba install RepeatMasker
https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/n..            No change
anaconda/pkgs/r/noarch                                        No change
https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/n..            No change
https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/l..            No change
anaconda/cloud/bioconda/noarch                                No change
anaconda/cloud/bioconda/noarch                                No change
anaconda/cloud/bioconda/linux-64                              No change
https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/l..   7.6MB @ 388.9kB/s 19.8s
anaconda/pkgs/r/linux-64                                      No change
anaconda/cloud/bioconda/linux-64                              No change
anaconda/cloud/conda-forge/noarch                   18.2MB @ 550.7kB/s 33.2s
anaconda/cloud/conda-forge/noarch                   18.2MB @ 401.6kB/s 44.2s
anaconda/cloud/conda-forge/linux-64                 43.7MB @ 738.8kB/s 60.0s
anaconda/cloud/conda-forge/linux-64                 43.7MB @ 728.8kB/s 1m:0.7s
critical libmamba [json.exception.type_error.302] type must be string, but is null

**Comment by BlenderWang9487** [comment]
Like I say, you are opening issue on a wrong repository. You should close this issue since your problem is not related to this deep learning model's repository.
And maybe you can open issue on the repo links that i provide
