### ISSUE TITLE
mamba-ssm for macos with M1 

### ISSUE THREAD

**Issue by freedom-cognit** [state-spaces/mamba#324]
I understand that currently mamba requires nvcc (Cuda) to install. Is there a version planned for MacOS M1? pytorch already support the MPS and it shall be nice to have mamba-ssm also install on MacOS on M1 and M2 laptops. A good portion of developers also use mac laptops for local testing (outside the docker containers)

**Comment by tridao** [comment]
No we have no plan for Mac.

**Comment by pmarreck** [comment]
There's really not a lot to it, the Mac already takes standard controllers like Playstation and Xbox, you could pretend you're an Xbox controller (which you already do) and it should work without too much additional work.

**Comment by purohit10saurabh** [comment]
I've implemented Mamba 1 and Mamba 2 SSM for macbook GPUs supporting both training and inference. It is available here: https://github.com/purohit10saurabh/mamba-ssm-macos
