### ISSUE TITLE
Different scan algorithm used in forward and backward selective scan kernel

### ISSUE THREAD

**Issue by minhkhoi1026** [state-spaces/mamba#329]
I observed that you used `cub::BLOCK_SCAN_WARP_SCANS` for scan operation in forward, but `cub::BLOCK_SCAN_RAKING` for backward. Are there any reason for this? Is there any big difference in term of memory, computation, and other performance characteristics between these two scan algorithms?

Forward reference:
````
struct Selective_Scan_fwd_kernel_traits {
    //....
    using BlockScanT = cub::BlockScan<scan_t, kNThreads, cub::BLOCK_SCAN_WARP_SCANS>;
````

Backward reference:
```
struct Selective_Scan_bwd_kernel_traits {
    //....
    using BlockScanT = cub::BlockScan<scan_t, kNThreads, cub::BLOCK_SCAN_RAKING>;
}
```
Thank you a lot for your help!

**Comment by tridao** [comment]
It's just tuning the speed. We choose whichever is faster.

**Comment by minhkhoi1026** [comment]
Thank you a lot! I guess so. Just curious whether there is any other reason!
