### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by talkinglim** [state-spaces/mamba#330]
It was working week ago then this occurs now.

```
torch version: 2.3.0+cu121
!pip install causal-conv1d>=1.2.0
!pip install mamba-ssm

working on google colab
```

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-35-38cc41754762>](https://localhost:8080/#) in <cell line: 2>()
      1 from tqdm import tqdm
----> 2 from mamba_ssm import Mamba
      3 import seaborn as sns
      4 import matplotlib.pyplot as plt
      5 import numpy as np

1 frames
[/usr/local/lib/python3.10/dist-packages/mamba_ssm/ops/selective_scan_interface.py](https://localhost:8080/#) in <module>
     14     causal_conv1d_cuda = None
     15 
---> 16 import selective_scan_cuda
     17 
     18 

ImportError: /usr/local/lib/python3.10/dist-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```

**Comment by mahirshahriar1** [comment]
Same here, since last night

**Comment by why-q** [comment]
Same here.

**Comment by zhangjingxian1998** [comment]
https://github.com/state-spaces/mamba/issues/12#issuecomment-1843706611
maybe this help

**Comment by talkinglim** [comment]
> [#12 (comment)](https://github.com/state-spaces/mamba/issues/12#issuecomment-1843706611) maybe this help

Does this work with colab? it looks like solution on running mamba-ssm on windows

**Comment by why-q** [comment]
> > [#12 (comment)](https://github.com/state-spaces/mamba/issues/12#issuecomment-1843706611) maybe this help
> 
> Does this work with colab? it looks like solution on running mamba-ssm on windows

I've tried this on Linux and it works, so colab should work as well

**Comment by talkinglim** [comment]
> > > [#12 (comment)](https://github.com/state-spaces/mamba/issues/12#issuecomment-1843706611) maybe this help
> > 
> > 
> > Does this work with colab? it looks like solution on running mamba-ssm on windows
> 
> I've tried this on Linux and it works, so colab should work as well.

apparently this approach is not viable on colab although they both runs on linux

**Comment by talkinglim** [comment]
I noticed my computation speed drop significantly from around 15 sample per second to 1 per second. is this related?

**Comment by talkinglim** [comment]
after using torch2.2 rather than torch 2.3, mamba-ssm can be run successfully and at the normal speed. Looks like the solution #12 (comment)(https://github.com/state-spaces/mamba/issues/12#issuecomment-1843706611) slows down the computation speed in colab.
