### ISSUE TITLE
Training with step 

### ISSUE THREAD

**Issue by norikazu99** [state-spaces/mamba#333]
Hello, 

Thanks a lot for this amazing repo I'm really enjoying using mamba in my experiments. I would like to know if it would be possible to use step during training without playing with cuda code? I would also like to know if it's possible to also be able to do so in chunks of 4 tokens for example?

**Comment by norikazu99** [comment]
Thank you very much for your fast response. I've been looking at the step fn. It seems that the causal_conv_1d already has a backward thanks to you, and I wouldn't want to modify your work. From what I can tell, most of the code will have to do with the backward of _selective_scan_update_kernel. Therefore, one can use the slower selective_state_update implemented in pytorch, and the backward would work out of the box? I'll be using this mainly for fine-tuning/curriculum learning so speed isn't too much of an issue. I have no experience with cuda/triton code but I'm willing to give it a shot if I have no other options.

**Comment by tridao** [comment]
Right you can use the pytorch version of selective_state_update.

**Comment by norikazu99** [comment]
Thank you very much for your help. I will be closing this issue. If I end up working on a backward for triton selective_state_update, I will share it.

**Comment by norikazu99** [comment]
Hello,
   Congratulations on your recent Mamba-2 paper, and thanks for sharing your work. Would it be possible to use step for training in module/mamba2.py when using selective_state_update. Or is it similar to Mamba v1 where I can only use the slower forward pass for this setup?

**Comment by tridao** [comment]
selective_state_update still only has the forward pass and not backward pass

**Comment by norikazu99** [comment]
Thank you for your help.
