### ISSUE TITLE
Question about loading data?

### ISSUE THREAD

**Issue by Hprairie** [state-spaces/mamba#336]
Hi, I have been really trying to understand the CUDA kernel provided and am slightly confused about why you are loading data in using `cub::BLOCK_LOAD_WARP_TRANSPOSE`. I am confused why data is stored in stripped format and not just direct format, and where this is happening. To me, all the checks in `selective_scan.cpp` make me think that data should be stored in a direct format. I understand how vector loading is working, but then am still confused why being directIO causes us to load in a direct form rather than a stripped form. Any guidance on this would be amazing, and thank you so much for the help and great work!

**Comment by tridao** [comment]
Data is stored contiguously (i think that's what you mean by direct). You can just print things out (with printf) to see which thread is loading what.

**Comment by Hprairie** [comment]
Thank you, I printed stuff out a realized I was being silly, you load the data in a stripped format and then transpose to make it direct. I think to improve access speeds. Thanks for the help!
