### ISSUE TITLE
Tips on debugging CUDA kernel

### ISSUE THREAD

**Issue by Hprairie** [state-spaces/mamba#339]
I'm writing bidirectionality support into the CUDA kernel. Should be able to get high L1 and L2 cache hit rates as portions of our sequence should still be in memory. I am curious if you have any recommendations to go about debugging. Compile time is the roughest, so I have removed some architectures while I test it. Any other suggestions or tips would be greatly appreciated. Thanks for such a great project, really does get me excited about this field.

**Comment by tridao** [comment]
You can comment out most of the options (e.g. only keep fp16 real length 128) so that it compiles faster.
I usually use printf to debug, sth like `if (threadIdx.x == 0 && blockIdx.x == 0 && blockIdx.y == 0 && blockIdx.z == 0) printf(blah); `

**Comment by Hprairie** [comment]
Thanks for the quick response!

**Comment by albertfgu** [comment]
I'll also mention that an "official" (endorsed by me at least) version of bidirectionality will appear on arXiv in the next two weeks :) would be cool to get lower-level implementation support for that!

**Comment by Hprairie** [comment]
I'm looking forward to it! At least for me, the way people did bidirectionality for Mamba with flipping and adding doesn't make any sense from a mathematical standpoint. I am working on a better extension of mamba to nd sequences and have a basic implementation for bidirectionality that is more mathematically sound. I look forward to the paper and would be more than happy to share the bidirectional code/change it to have low-level support for this paper.

**Comment by FilippoBotti** [comment]
Could you please provide the command that you use in order to recompile the kernel? Because i run
`python3 setup.py install` but i do not think this is the proper way to do it

**Comment by Hprairie** [comment]
`pip install -e .` is what I use, you need to edit the `setup.py` if you want to customize the install.

**Comment by FilippoBotti** [comment]
Do you add the `selective_scan_fwd{bwd}_kernel.cuh` in your setup.py? Because it seems to be ignored when i use `python3 setup.py install` command (which is relatively fast, but I also think this is why). 
The only way it seems to work is when I first delete the build folder and then run `python3 setup.py install` in order to recompile the .cuh file.
Thanks for your help

**Comment by Hprairie** [comment]
I see what you are saying. Yes, you have to delete the build and then just rerun. The compiler doesn't know that header files have changed, and thus it won't do anything unless you delete the build folder. Deleting build is what I did and it worked fine. The best thing to reduce compile time was to remove the number of templates and also only compile to sm architecture on my machine. Np, and gl
