### ISSUE TITLE
BLOCK_N in _layer_norm_fwd()

### ISSUE THREAD

**Issue by vidavakil** [state-spaces/mamba#340]
Hello,

First, I wanted to thank the authors of Mamba for your amazing work, and your masterful codebase. I have been tweaking it in many directions for a while now, and it's been a great playground.

I have a question regarding the implementation of layer norm (and I notice it is likely derived from code at triton.org, [here](https://triton-lang.org/main/getting-started/tutorials/05-layer-norm.html)):

_layer_norm_fwd() uses the following two lines to compute a BLOCK_N for the given N=x.shape[0]

    MAX_FUSED_SIZE = 65536 // x.element_size()
    BLOCK_N = min(MAX_FUSED_SIZE, triton.next_power_of_2(N))

It makes sense for BLOCK_N to be the next multiple of memory cache line size (e.g., next multiple of 128), or more precisely, some function of N, x.element_size(), warp_size and cache_line_size, but instead this code uses next_power_of_2(). This sounds excessive, and I wonder if it's a mistake that has been replicated in code bases that copy/use the triton implementation of layer norm. Of course it is common/standard for models to have a power-of-two d_model, and thus this may not cause any overhead. But I wanted to bring it up to your attention and see what your thoughts are.

https://github.com/state-spaces/mamba/blob/a07faffa36a7b89e754b5de972418475bcdd77b6/mamba_ssm/ops/triton/layernorm.py#L150C35-L150C57

**Comment by tridao** [comment]
Have you tried non-power-of-2? Triton doesn't support non-power-of-2 afaik.

**Comment by vidavakil** [comment]
No, I had not tried it. My GPU was busy when I noticed that line of code (and still is), and I thought of asking anyway. You must be right, according to what is said [here](https://openai.com/index/triton/). Thanks for your time responding.
