### ISSUE TITLE
Clarification on Selective Copying Task Settings in Mamba

### ISSUE THREAD

**Issue by MinhZou** [state-spaces/mamba#343]
I have carefully read the article and I was wondering if you could provide the settings for the selective copying task?  I am referring to the code from the S4 paper, but I am unsure about the experimental setup used in the paper, such as how to set n_eval and n_train, and how to configure the 'static' setting.

I am looking at the .yaml files from the S4 repository:
https://github.com/state-spaces/s4/blob/e757cef57d89e448c413de7325ed5601aceaac13/configs/dataset/copying.yaml
https://github.com/state-spaces/s4/blob/e757cef57d89e448c413de7325ed5601aceaac13/configs/experiment/synthetic/s4-copying.yaml

Some specific settings:
name: copying
l_noise: 100 # length
l_memorize: 10  # number of tokens to memorize
n_tokens: 10  # alphabet size
variable: false # Randomly distribute memorization tokens throughout sequence instead of frontloading them
variable_length: false # Randomize number of tokens to memorize
n_train: 10000 # Training samples per epoch (random)
n_eval: 1000 # Evaluation samples per epoch (fixed)
one_hot: false
reverse: false
static: false
lag: false

Could you please clarify the appropriate settings for reproducing the selective copying task experiments from the mamba paper? Any guidance would be greatly appreciated.

**Comment by albertfgu** [comment]
I think the selective copying task was not released. I can see if I ever have some time to take a look and try to release it, but unlikely in the near future

The task shouldn't be too different from the copying tasks that are in there though, but you would have to actually modify the generation code and add some settings

**Comment by MinhZou** [comment]
Thank you for your reply and attention. Based on the generation code in [S4,](https://github.com/state-spaces/s4/blob/e757cef57d89e448c413de7325ed5601aceaac13/src/dataloaders/datasets/copying.py
) which has already covered the copying memory task and selective copying task, my simple implementation is available at [selective-copying-mamba.](https://github.com/MinhZou/selective-copying-mamba) I hope my implementation is correct and without issues.

**Comment by MinhZou** [comment]
Thank you for your reply and attention. Based on the generation code in [S4,](https://github.com/state-spaces/s4/blob/e757cef57d89e448c413de7325ed5601aceaac13/src/dataloaders/datasets/copying.py
) which has already covered the copying memory task and selective copying task, my simple implementation is available at [selective-copying-mamba.](https://github.com/MinhZou/selective-copying-mamba) I hope my implementation is correct and without issues.
