### ISSUE TITLE
Small Mistake in Mamba2 - Eq (9)

### ISSUE THREAD

**Issue by vasqu** [state-spaces/mamba#350]
First of all, great work!

I think I found a small mistake in equation 9 (section 4.1.1) of the recent Mamba 2 paper:
![image](https://github.com/state-spaces/mamba/assets/73884904/a5b5e551-e487-48e3-abeb-52e8a3ec3d92)
The last projection should be 
`𝑌 = 𝑀𝑉 (T, P)`
instead of
`𝑌 = 𝐺𝑉 (T, P)`.

**Comment by albertfgu** [comment]
you're right, thanks for the catch! will be updated in next version
