### ISSUE TITLE
[Mamba2] Loss is all NaN during training

### ISSUE THREAD

**Issue by XiudingCai** [state-spaces/mamba#353]
Hi there! I've replaced Mamba1 with Mamba2 for time-series tasks. During training, I noticed that the network's output starts off normal but then suddenly all predictions turn into NaN. However, I've never encountered this issue when using Mamba1. Not sure what's going wrong here.

tensor([[[ 8.8187e-02, -1.3473e+00, -1.3800e+00,  ..., -6.8665e-01,
          -1.3425e+00,  2.5207e-02],
         [ 1.2011e+00, -1.3547e+00, -1.4719e+00,  ..., -4.8274e-01,
          -1.1846e+00,  5.7640e-02],
         [ 9.8438e-01, -1.0468e+00, -1.1294e+00,  ..., -4.6929e-01,
          -1.0779e+00,  3.7898e-02],
         ...,
         [ 8.1007e-01, -1.2855e+00, -1.4126e+00,  ..., -7.0804e-01,
          -1.2346e+00,  2.1755e-02],
         [ 1.1818e+00, -1.2443e+00, -1.3662e+00,  ..., -4.7275e-01,
          -1.0384e+00,  4.3553e-02],
         [ 8.6926e-01, -1.3135e+00, -1.4032e+00,  ..., -4.9079e-01,
          -1.0833e+00,  4.4128e-02]],

        [[-1.2445e+00,  5.8041e-01,  4.7143e-01,  ..., -1.4827e+00,
           1.5187e-01, -2.5252e-02],
         [-2.3478e-01,  2.6395e-01,  2.5168e-01,  ..., -6.8435e-01,
           5.0564e-02,  3.4234e-02],
         [-6.3810e-01,  6.2939e-01,  7.2757e-01,  ..., -1.0254e-01,
           5.0687e-01, -1.3203e-02],
         ...,
         [-7.0284e-01,  2.6054e-01,  2.7131e-01,  ...,  2.0390e-01,
           4.4316e-02, -6.6330e-02],
         [-1.0240e-01,  6.6480e-01,  5.1391e-01,  ...,  1.6077e-01,
           7.5540e-01,  5.7014e-03],
         [-4.1051e-01,  5.1565e-01,  5.4024e-01,  ..., -2.1707e-01,
           4.9277e-01, -1.6089e-02]],

        [[-8.4259e-01,  6.1950e-01,  5.9708e-01,  ..., -2.2316e+00,
           4.5017e-01, -3.4229e-02],
         [-4.6926e-01,  7.4733e-01,  8.6743e-01,  ..., -1.3958e+00,
           6.1399e-01,  9.5260e-03],
         [-4.5961e-01,  8.1573e-01,  9.1278e-01,  ..., -1.1856e+00,
           4.7596e-01, -1.1733e-02],
         ...,
         [-4.4962e-01,  3.5888e-01,  3.4970e-01,  ..., -5.8329e-01,
          -1.4196e-02,  3.3069e-02],
         [-4.6131e-01,  3.5883e-01,  3.6132e-01,  ..., -7.7780e-01,
           5.2682e-02,  3.5626e-02],
         [-5.3999e-01, -2.6149e-02, -4.9402e-02,  ..., -7.7034e-01,
          -2.8297e-01,  2.1957e-02]],

        ...,

        [[-1.0582e+00,  4.3065e-01,  5.3543e-01,  ..., -1.4205e-01,
           2.8086e-01, -1.6592e-03],
         [-7.9813e-01, -3.5804e-02,  1.0039e-01,  ..., -9.0201e-01,
          -1.6354e-01,  3.6617e-02],
         [-7.8089e-01,  3.5184e-02, -5.3098e-03,  ..., -8.5178e-01,
          -8.3759e-02,  5.5612e-02],
         ...,
         [-7.2412e-01, -3.0382e-02, -7.9767e-02,  ..., -1.0399e+00,
          -1.5293e-01,  8.7803e-02],
         [-5.8368e-01, -2.8590e-01, -2.0579e-01,  ..., -4.3772e-01,
          -3.9755e-01,  8.4434e-02],
         [-7.9389e-01, -1.3482e-01, -1.5319e-01,  ..., -8.4759e-01,
          -3.3613e-01,  7.0270e-02]],

        [[-3.9449e-01, -7.2935e-01, -7.9978e-01,  ..., -8.4329e-01,
          -7.0988e-01, -2.7378e-02],
         [-3.9742e-01, -3.3451e-01, -2.9300e-01,  ..., -7.6541e-02,
          -2.8140e-01,  4.5581e-02],
         [ 3.4276e-02, -2.3654e-01, -1.3946e-01,  ...,  2.6645e-01,
           1.6401e-02,  2.2244e-02],
         ...,
         [-1.6183e-01,  8.9145e-02,  6.1024e-02,  ...,  3.5869e-01,
           2.1649e-01, -2.2375e-02],
         [-2.2773e-01,  4.6242e-01,  4.4655e-01,  ...,  6.5469e-01,
           6.7243e-01,  1.3407e-02],
         [-3.5365e-01,  5.3206e-01,  5.7472e-01,  ...,  5.5110e-01,
           6.8992e-01, -3.0700e-04]],

        [[-6.8191e-01, -1.2392e+00, -1.0938e+00,  ..., -6.1562e-01,
          -1.3362e+00, -1.6211e+01],
         [ 1.0634e-01, -1.2975e+00, -1.4086e+00,  ..., -6.1917e-01,
          -1.4895e+00, -7.6272e+00],
         [-3.0046e-01, -8.1921e-01, -8.4260e-01,  ..., -4.1267e-01,
          -1.0870e+00, -7.9071e+00],
         ...,
         [-5.4683e-01, -1.2326e+00, -1.3735e+00,  ..., -5.3598e-01,
          -1.3068e+00, -8.5222e+00],
         [ 1.4033e-01, -9.0521e-01, -7.3204e-01,  ..., -1.8536e-01,
          -9.2793e-01, -4.5445e+00],
         [ 9.6245e-03, -1.0578e+00, -1.2377e+00,  ..., -3.6130e-01,
          -1.0910e+00, -9.0167e+00]]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]], device='cuda:0',
       grad_fn=<AddBackward0>)

**Comment by tyshiwo1** [comment]
Same issue in [#352 ](https://github.com/state-spaces/mamba/issues/352)

**Comment by bio-mlhui** [comment]
I lower down the chunk size to 1 and it is slow but no NAN

**Comment by XiudingCai** [comment]
Same issue in https://github.com/state-spaces/mamba/issues/352
