### ISSUE TITLE
Chunk Size and Nan Loss

### ISSUE THREAD

**Issue by bio-mlhui** [state-spaces/mamba#354]
I lower down the chunk size to 1 and the loss will not become Nan, but the training is much slower

**Comment by tyshiwo1** [comment]
I found this line of code causes NaN of `dx`
https://github.com/state-spaces/mamba/blob/main/mamba_ssm/ops/triton/ssd_combined.py#L176

**Comment by bio-mlhui** [comment]
seems this line of code is highly related to parameter A (dA_cs_k) and the chunk_size (K_MAX)
