### ISSUE TITLE
Mamba2 Parallelization questioned. Very similar to the 'UltraLight VM-UNet: Parallel Vision Mamba Significantly Reduces Parameters for Skin Lesion Segmentation' article.

### ISSUE THREAD

**Issue by Nobuttero** [state-spaces/mamba#364]
Hi, we found your mamba2 parallelization very similar to the previous '**UltraLight VM-UNet: Parallel Vision Mamba Significantly Reduces Parameters for Skin Lesion Segmentation**' in lightweight medical image segmentation. And there is no discussion or citation of it in the paper. Wu et al. have already discussed the advantage of significant parameter reduction by parallelizing mamba, but what is the significance of mamba2?

Parallelization in mamba2:
![图片](https://github.com/state-spaces/mamba/assets/152582131/c5cfa532-656d-4b2d-b417-65a05e8df416)

Parallelization in UltraLight VM-UNet:
![图片](https://github.com/state-spaces/mamba/assets/152582131/388ec352-9a65-4218-a97f-274e9a8d9c6d)

**Comment by albertfgu** [comment]
this doesn't seem to be talking about the same form of parallelism (tensor parallelism). i don't think these contributions are very related; the architectural modifications are not the main focus of mamba-2

note that mamba-2 was finalized more than 6 months ago! we're very happy that this paper and others are excited about applying and improving mamba, but, we don't have room to discuss every follow-up work :(
