### ISSUE TITLE
Question: Why does mamba use LayerNorm instead of RMSNorm?

### ISSUE THREAD

**Issue by devzzzero** [state-spaces/mamba#381]
according to <https://arxiv.org/abs/1910.07467> RMSNorm is now considered to be a better choice (at least for transformer and related architectures). 

Is there something specific to mamba that makes the performance advantage of RMSNorm not  relevant? or is there something specific in S4/mamba that makes LayerNorm a better choice for mamba?

Upon further examination of the code, it looks like RMSNorm is there, but it's unclear to me why it is gated? Can some kind soul clarify the reasoning behind this?

Thank you!

**Comment by tridao** [comment]
We use RMSNorm in Mamba.

**Comment by devzzzero** [comment]
> We use RMSNorm in Mamba.

Thank you for your response. Are your mamba models in hf using RMSNorm? (your paper and parts of the code specifically mention LayerNorm, so I was wondering)

**Comment by tridao** [comment]
Afaik all Mamba and Mamba-2 models use RMSNorm.
