### ISSUE TITLE
Unable to install mamba-ssh

### ISSUE THREAD

**Issue by DeShinHwa** [state-spaces/mamba#392]
I am trying to install mamba-ssh and encountered this error. 

pip install mamba-ssm==2.0.4
Collecting mamba-ssm==2.0.4
  Using cached mamba_ssm-2.0.4.tar.gz (82 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in c:\users\hwade\appdata\local\programs\python\python311\lib\site-packages (from mamba-ssm==2.0.4) (2.1.0+cu121)
Requirement already satisfied: packaging in c:\users\hwade\appdata\local\programs\python\python311\lib\site-packages (from mamba-ssm==2.0.4) (24.0)
Collecting ninja (from mamba-ssm==2.0.4)
  Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata (5.4 kB)
Requirement already satisfied: einops in c:\users\hwade\appdata\local\programs\python\python311\lib\site-packages (from mamba-ssm==2.0.4) (0.7.0)
INFO: pip is looking at multiple versions of mamba-ssm to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement triton (from mamba-ssm) (from versions: none)
ERROR: No matching distribution found for triton

my Pytorch version 2.1.0, cuda 12.1.0. It seems like there's problem in triton package?

**Comment by DeShinHwa** [comment]
> I have the same problem.How did you solve that problem?

Hi, mamba-ssm only support in the Linux system. I encountered this problem when trying to pip install in Windows. 

Therefore, I use wsl2(a linux environment) to install it and should be fine. 

Best regard
De Shin

**Comment by supersuperdong** [comment]
> > I have the same problem.How did you solve that problem?
> 
> Hi, mamba-ssm only support in the Linux system. I encountered this problem when trying to pip install in Windows.
> 
> Therefore, I use wsl2(a linux environment) to install it and should be fine.
> 
> Best regard De Shin

thanks
