### ISSUE TITLE
Model checkpoint parameters are stored in FP16, why?

### ISSUE THREAD

**Issue by chen-yingfa** [state-spaces/mamba#397]
It seems that, at least for Mamba-2, the released checkpoints are stored in FP16, and consequently, directly running inference will be in FP16 as well. 

1. What is the reason of FP16 over using BF16? 
2. Should we convert the parameters back to BF16 for training? 
3. What about inference?

Thanks in advance.

**Comment by tridao** [comment]
FP16 seems more popular for inference.
We use mixed precision (fp32-bf16) for training.
