### ISSUE TITLE
Error with Mamba2 example code

### ISSUE THREAD

**Issue by zheyuanhu01** [state-spaces/mamba#398]
Thanks the authors for the wonderful work and the great documentation!

I have a question when running Mamba2 example on Google Colab. I tried the code.

```
import torch
from mamba_ssm import Mamba2

batch, length, dim = 2, 64, 32
x = torch.randn(batch, length, dim).cuda()

model = Mamba2(
    # This module uses roughly 3 * expand * d_model^2 parameters
    d_model=dim, # Model dimension d_model
    d_state=64,  # SSM state expansion factor, typically 64 or 128
    d_conv=4,    # Local convolution width
    expand=2,    # Block expansion factor
    headdim=4
).cuda()
y = model(x)
assert y.shape == x.shape
```

Besides mamba-ssm package, I also installed causal-conv1d and upgraded trition.

However, I got the error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-2-174bde3805b6>](https://localhost:8080/#) in <cell line: 15>()
     13     headdim=4
     14 ).cuda()
---> 15 y = model(x)
     16 assert y.shape == x.shape

18 frames
[/usr/local/lib/python3.10/dist-packages/triton/compiler/backends/cuda.py](https://localhost:8080/#) in make_llir(src, metadata, options, capability)
    171             add_external_libs(src, names, paths)
    172         # TritonGPU -> LLVM-IR
--> 173         ret = translate_triton_gpu_to_llvmir(src, capability, tma_infos, runtime.TARGET.NVVM)
    174         if len(tma_infos) > 0:
    175             metadata["tensormaps_info"] = parse_tma_info(tma_infos, metadata["ids_of_folded_args"])

IndexError: map::at

Any comments on this?

Thanks and best regards.

**Comment by tridao** [comment]
It's a Triton error. You can search on the triton repo issues.

**Comment by wzy1845** [comment]
hi I also encountered the same problem. How did you solve it in the end? thank!

**Comment by ZQuang2202** [comment]
> hi I also encountered the same problem. How did you solve it in the end? thank!

You could try [this](https://github.com/state-spaces/mamba/issues/361#issuecomment-2748443402).
