### ISSUE TITLE
Grad Norm: nan when using mamba in Dinov2 task

### ISSUE THREAD

**Issue by yangtiming** [state-spaces/mamba#400]
Thank you for your nice work. I tried to use the mamba(v1/v2) to Dinov2. However, I have some problems causing the Grad Norm: nan. 
Here is the way I debug:

    for name, param in self.student.named_parameters():
        if param.requires_grad:
            if param.grad is not None:
                param_norm = param.grad.norm()
                param_values = param.data
                grad_values = param.grad
                logger.info(f"{name} - Grad Norm: {param_norm}")

However, 
    
    backbone._fsdp_wrapped_module.cls_token - Grad Norm: nan
    backbone._fsdp_wrapped_module.pos_embed - Grad Norm: nan
    backbone._fsdp_wrapped_module.mask_token - Grad Norm: nan
    backbone._fsdp_wrapped_module.norm_f.weight - Grad Norm: 4.881098720943555e-05
    backbone._fsdp_wrapped_module.norm_f.bias - Grad Norm: 3.305985956103541e-05
    backbone._fsdp_wrapped_module.patch_embed.proj.weight - Grad Norm: nan
    backbone._fsdp_wrapped_module.patch_embed.proj.bias - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.mixer.dt_bias - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.mixer.A_log - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.mixer.D - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.mixer.in_proj.weight - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.mixer.conv1d.weight - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.mixer.conv1d.bias - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.mixer.out_proj.weight - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.norm.weight - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.0.norm.bias - Grad Norm: nan
    .....
    backbone._fsdp_wrapped_module.blocks.5.mixer.D - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.5.mixer.in_proj.weight - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.5.mixer.conv1d.weight - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.5.mixer.conv1d.bias - Grad Norm: nan
    backbone._fsdp_wrapped_module.blocks.5.mixer.out_proj.weight - Grad Norm: nan
    dino_head._fsdp_wrapped_module.mlp.0.weight - Grad Norm: 0.0
    dino_head._fsdp_wrapped_module.mlp.0.bias - Grad Norm: 0.0
    dino_head._fsdp_wrapped_module.mlp.2.weight - Grad Norm: 0.0
    dino_head._fsdp_wrapped_module.mlp.2.bias - Grad Norm: 0.0
    dino_head._fsdp_wrapped_module.mlp.4.weight - Grad Norm: 0.0
    dino_head._fsdp_wrapped_module.mlp.4.bias - Grad Norm: 0.0
    dino_head._fsdp_wrapped_module.last_layer.weight_g - Grad Norm: 0.0
    dino_head._fsdp_wrapped_module.last_layer.weight_v - Grad Norm: 0.0

This problem happens when I try to use the below in MambaV1(v1.1.1):

    from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn

Or, I try to use MambaV2(V2.0.4):
    
    mamba_split_conv1d_scan_combined
  

Can somebody help me to deal with this problem?

**Comment by tridao** [comment]
Please send a script that we can reproduce, e.g. by saving tensors right before a function call that causes NaN:
```
### torch.save(a bunch of tensors)
```
```
tensors = torch.load(blah)
# calling func on tensors cause NaN.
```

**Comment by tridao** [comment]
Does that cause the *output* to be NaN?
You mentioned gradient being NaN. How do we reproduce that from the saved tensors to get NaN gradient?

**Comment by tridao** [comment]
e.g. can you post a short script that loads the tensors, call the relevant function, then show that the function produces NaN?

**Comment by yangtiming** [comment]
Thank you for your reply. Finally, I found the problem caused by the mixed_precision. Do you have any good ideas to handle this problem? In my view, I think torch.cuda.amp maybe good to deal with it.

**Comment by tridao** [comment]
We use torch.amp. I'm not familiar with FSDP configs.

**Comment by chokevin8** [comment]
@yangtiming Hi, I had a similar issue where I ran into nan issues with utilizing dinov2 with mamba, utilizing DDP (not even FSDP as you mentioned). However I do plan to expand it to FSDP in the future, did you get it figured out by any chance? Thank you!

**Comment by yangtiming** [comment]
> @yangtiming Hi, I had a similar issue where I ran into nan issues with utilizing dinov2 with mamba, utilizing DDP (not even FSDP as you mentioned). However I do plan to expand it to FSDP in the future, did you get it figured out by any chance? Thank you!

The basic solution is to change the dim from 384 -> 256. (multiple of 8, maybe you can see some question about it)

**Comment by yangtiming** [comment]
> Oh, wow so did that simple solution fix the problem for you and enable the FSDP training for mamba or did you also have to do something else? Thanks for your quick reply as well :)
> 
> I'm trying a higher image resolution training so maybe I might try embedding dimension of 512, but that will depend on my GPU limit I guess...

Yes, only change the dim(I think the dim of mamba should be 256,512,etc), and anything bad about (mamba +dinov2) disappears.

**Comment by chokevin8** [comment]
Thank you, that helps a lot! If you don't mind, can you tell me if you used these configs for student & teacher?
backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp32
        reduce_dtype: bf16
        buffer_dtype: fp16
Also if you don't mind, may I ask what modifications you have made to make mamba implementation for FSDP (auto_wrap_policy, chunking model block ,etc)? Thank you so much! 👍

**Comment by yangtiming** [comment]
> Thank you, that helps a lot! If you don't mind, can you tell me if you used these configs for student & teacher?
> backbone:
> sharding_strategy: SHARD_GRAD_OP
> mixed_precision:
> param_dtype: fp32
> reduce_dtype: bf16
> buffer_dtype: fp16
> Also if you don't mind, may I ask what modifications you have made to make mamba implementation for FSDP (auto_wrap_policy, chunking model block ,etc)? Thank you so much! 👍

param_dtype: bf16
reduce_dtype: fp32
buffer_dtype: fp32

chunking model block =0

no change in other part

**Comment by chokevin8** [comment]
I see! So block_chunks = 0 will run fine, didn't know that, thank you! Bless you for all of the help, much appreciated :)

**Comment by chokevin8** [comment]
https://github.com/state-spaces/mamba/issues/352
https://github.com/state-spaces/mamba/issues/345

@yangtiming  Seems like it is only for Mamba-2 that requires the embedding dimension or d_model to be multiples of 256 or 512, but did you find that Mamba would require the same? Because currently I am using Mamba, not Mamba-2 for DINOv2. Thank you :)

**Comment by yangtiming** [comment]
> #352 #345
> 
> @yangtiming Seems like it is only for Mamba-2 that requires the embedding dimension or d_model to be multiples of 256 or 512, but did you find that Mamba would require the same? Because currently I am using Mamba, not Mamba-2 for DINOv2. Thank you :)

If you are using Vim, then try to set             
rms_norm=False, fused_add_norm=False. 

Also, you can set 

param_dtype: fp32
reduce_dtype: fp32  ( I forget, maybe fp16)
buffer_dtype: fp32 ( I forget, maybe fp16)

It will work well.

**Comment by chokevin8** [comment]
> > #352 #345
> > @yangtiming Seems like it is only for Mamba-2 that requires the embedding dimension or d_model to be multiples of 256 or 512, but did you find that Mamba would require the same? Because currently I am using Mamba, not Mamba-2 for DINOv2. Thank you :)
> 
> If you are using Vim, then try to set rms_norm=False, fused_add_norm=False.
> 
> OR, you can set
> 
> param_dtype: fp32 reduce_dtype: fp32 ( I forget, maybe fp16) buffer_dtype: fp32 ( I forget, maybe fp16)
> 
> It will work well.

Hmm, yes I am utilizing the Vim architecture and I modified the code to make DINOv2 training work (I'm sure you did this as well). The default currently is rms_norm and fused_add_norm both equal to True for Vim, and setting these to False would make the training stable (no more nan's and convergence)? 

Interesting how doing add and norm separately by setting it to False makes the training better...And yes I will try those dtypes, thank you so much!

**Comment by chokevin8** [comment]
Hello, I'm sorry to keep asking questions, but may I ask which environment (CUDA, PyTorch version, mamba-ssm, and causal_conv1d versions) you utilized to train Vision Mamba (Vim) with DINOv2 task utilizing bfloat16? When I utilize fp32 or fp16 it runs fine (fp16 will give unstable training though) and code will compile, but bfloat16 keeps giving me errors like this:


```
TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: Optional[torch.Tensor], arg5: Optional[torch.Tensor], arg6: bool) -> torch.Tensor
```

I'm currently utilizing torch 2.1.1, causal_conv1d 1.1.1, mamba-ssm==1.2.0.post1. I've tried changing up the torch, causal_conv1d, mamba-ssm versions, but with no success, still cannot train with bfloat16. Any help would be appreciated!

**Comment by chokevin8** [comment]
Also, as mentioned as a solution in this [issue](https://github.com/state-spaces/mamba/issues/40#issuecomment-1849095898), I don't have this problem due to old GPU since my GPU CCC is >=7. (Utilizing V100 or/and A100)

**Comment by Jon-Zbw** [comment]
> 我们使用 torch.amp。我不熟悉 FSDP 配置。

I've had the problem of loss and grad_norm for Nan after several epochs, currently disabling AMP(switching to fp32) and reducing the learning rate to 5e-6 (origin is 5e-4) to alleviate it, but the loss drops very slowly, is there any other way to fix it?
