### ISSUE TITLE
ngroups and tp

### ISSUE THREAD

**Issue by patronum08** [state-spaces/mamba#406]
Thank you for your work on mamba2. I am encountering some difficulties in understanding `ngroups` and `tp`. I have several questions and am looking forward to your answers.

1) When `tp` encounters a multi-head design, does it actually place different heads on different GPUs? If so, there should be `n_heads % world_size == 0`, but there doesn't seem to be a related assertion in the code.
2) The paper states that `tp` results in different `B` and `C` on different GPUs (where `B` and `C` on different GPUs act on different parts of `d_inner`). The code mentions that there are `ngroups` copies, meaning each GPU has `ngroups/tp_size` of `B` and `C`. How are these `ngroups/tp_size` `B` and `C` used on the same GPU? Does each individual copy of `B` and `C` act on each `d_inner/ngroups` dimensions? If so, does this imply that `d_inner % ngroups == 0`?

**Comment by tridao** [comment]
1. Yes we need `n_heads % world_size == 0`.
2. Yes each copy of B and C act on `d_inner / ngroups` dimensions. We need `d_inner % ngroups == 0`.

**Comment by patronum08** [comment]
Thank you for your reply, it's very helpful!
