### ISSUE TITLE
Input output dimension

### ISSUE THREAD

**Issue by zyw0o1564** [state-spaces/mamba#409]
“如果曼巴模型的输出维度不一定等于输入维度，我应该如何配置它？我使用的是曼巴模型，其中输入是三维数据，输出也是三维数据，但我只想要一维输出。

**Comment by tridao** [comment]
In terms of dimensions Mamba is no different than MLP or Attention. So this question is not specific to Mamba.
You can do whatever is standard in your task (taking mean, taking the first element, last element, etc.).
