### ISSUE TITLE
Failed to build installable wheels for some pyproject.toml based projects (mamba-ssm)

### ISSUE THREAD

**Issue by ywh939** [state-spaces/mamba#421]
Building wheels for collected packages: mamba-ssm
  Building wheel for mamba-ssm (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]

      torch.__version__  = 1.13.1+cu116

      running bdist_wheel
      Guessing wheel URL:  https://github.com/state-spaces/mamba/releases/download/v2.1.0/mamba_ssm-2.1.0+cu118torch1.13cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
      error: <urlopen error [Errno 104] Connection reset by peer>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mamba-ssm
  Running setup.py clean for mamba-ssm
Failed to build mamba-ssm
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (mamba-ssm)

**My environment is based on docker container:**
GPU: 3090
image: nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04
python: 3.10.13
pytorch: 1.13.1

I try to install mamba by two ways: pip install mamba-ssm and pip install . from repository
but all failed.

**Comment by ywh939** [comment]
<img width="606" alt="1719313621585" src="https://github.com/state-spaces/mamba/assets/27114849/5f312f95-7f3e-4446-a707-e9c186215ea0">

I find the release version named like "...cu118torch..."

Could it be that the minimum required cuda version is 11.8?

**Comment by ywh939** [comment]
the above happened at newest version: v2.1.0，v1 and lower than v2.1.0 can build well

**Comment by tridao** [comment]
I can download this link `https://github.com/state-spaces/mamba/releases/download/v2.1.0/mamba_ssm-2.1.0+cu118torch1.13cxx11abiFALSE-cp310-cp310-linux_x86_64.whl` just fine. You should try again.

**Comment by ywh939** [comment]
> I can download this link `https://github.com/state-spaces/mamba/releases/download/v2.1.0/mamba_ssm-2.1.0+cu118torch1.13cxx11abiFALSE-cp310-cp310-linux_x86_64.whl` just fine. You should try again.

it works.
