### ISSUE TITLE
mamba2 triton.runtime.autotuner.outofresources: out of resource: shared memory, required: 294912, hardware limit: 49152. reducing block sizes or `num_stages` may help

### ISSUE THREAD

**Issue by hhhhpaaa** [state-spaces/mamba#438]
Mamba2 is having problems running. mamba1 works fine.
I tried to change the input dimension, but I get the same error every time. I tried to reduce the model size and input tensor size, but each time I get the same amount of shared memory required for the error.
The environment is set to nividia docker cuda 11.8, 16G RAM, GTX 1050ti (4G).
The compilation steps are detailed at [issues 40](https://github.com/state-spaces/mamba/issues/40#issuecomment-1849095898)
I compiled both version 2.2 and 2.1 and got the same error.
I want to apply mamba2 to Few-shot learning.
I think it's a code problem rather than a lack of computing power on my computer.

**Comment by hhhhpaaa** [comment]
I just compiled mamba_ssm=2.2 again and Mamba2 worked fine!
In fact, triton had problems with version 2.1.0. i reinstalled triton=2.3.1 to compile again, and mamba2 finally worked.
Detailed environment is python=3.10, pytorch=2.1.1=cuda118, causal-conv1d=1.3.0.
In my environment, `triton=2.1.0` triggered the outofresources bug. it is recommended to limit `triton >= 2.3.1`.

**Comment by xuejiaxing** [comment]
May I ask where to install triton-nightly? I really can't find it.

**Comment by hhhhpaaa** [comment]
> May I ask where to install triton-nightly? I really can't find it.

You can try running `pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly`.

**Comment by xuejiaxing** [comment]
Thank you very much for your reply! However, this problem occurred after I installed triton-nightly. I wonder if you have encountered it and have a solution.

AttributeError: module 'triton.language.math' has no attribute 'log1p'. Did you mean: 'log2'?

**Comment by xuejiaxing** [comment]
Thank you very much for your reply!

**Comment by zju-sqs** [comment]
> > May I ask where to install triton-nightly? I really can't find it.
> 
> You can try running `pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly`.

How did u solved triton-nightly 3.0.0 run on sm 61? I try to run mamba2 on 1080ti, but occurred with 
raise RuntimeError(f'Internal Triton PTX codegen error: \n{log}')
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/tmpzyj70w1u.ptx, line 24458; error   : Feature '.acq_rel' requires .target sm_70 or higher
ptxas fatal   : Ptx assembly aborted due to errors
