### ISSUE TITLE
When to use ngroups in mamba-v2?

### ISSUE THREAD

**Issue by ScottHoang** [state-spaces/mamba#442]
In my use case, I am applying Pytorch's FSDP on mamba over 8 GPUs. Should ngroups be increased to 8?

**Comment by tridao** [comment]
No it's not necessary. You should increase ngroups if you're using tensor parallel.

**Comment by ScottHoang** [comment]
Thank you! I appreciate the answer.

Also, unlike the original mamba, mamba2-2.7b (on HF) does not contain a Feed-forward network (intermediate value is set to 0) on the hugging face. Is this correct?

**Comment by tridao** [comment]
Neither mamba1 or 2 have feedforward. The default is `d_intermediate = 0`.

**Comment by ScottHoang** [comment]
mamba 1 : https://huggingface.co/state-spaces/mamba-2.8b-hf/blob/main/config.json 
has an intermediate value of twice the model dimension.

**Comment by tridao** [comment]
That's the HF config. I'm not familiar with how it's impelmented in HF transformer. They might use "intermediate_size" to mean sth else (not the feedforward). 
Here's the config used for the implementation in this repo:
https://huggingface.co/state-spaces/mamba-2.8b/blob/main/config.json

**Comment by ScottHoang** [comment]
Got it! Thank you!

**Comment by oniwakaa** [comment]
placeholder
