### ISSUE TITLE
Understanding Pass State Associative Scan

### ISSUE THREAD

**Issue by Hprairie** [state-spaces/mamba#443]
Hey Tri and Albert great work on Mamba2. In the blog post for Mamba2, you state that in your optimized triton kernel you use an associative scan rather than the full matrix multiplication. Originally I took this as a parallel associative scan like in the original mamba, however, when digging through the code this doesn't seem to be the case and is just a sequential scan. Is the limitation of a parallel scan being used triton or something else? 

I can see that it wouldn't be helpful for small sequences as we are already chunking into T/Q sections (T being the length and Q the block size, as written in Part III of the blog post), however, for large sequences I would expect a fair amount of gain. Lmk your thoughts, thanks!

**Comment by tridao** [comment]
It's just about how you schedule the parallel workers. After chunking the sequence is not very long (e.g. seqlen = 2k, chunk_size = 256 -> 8 chunks). In that case it's better to parallelize along the other dimension rather than the seqlen dimension.
In other cases where seqlen is long it might be advantageous to parallelize along seqlen dimension (e.g. with parallel scan instead of sequential scan).

**Comment by Hprairie** [comment]
Thank you, makes sense.

**Comment by Hprairie** [comment]
Sorry to bother you again @tridao, but I am curious about when developing the Triton kernel for `ssd_state_passing`, did you try experimenting with the dual form of mamba2 and thus using single matrix multiplication in the kernel rather than the associative scan? If using the tensor cores makes such a huge improvement for `ssd_chunk_scan`, then shouldn't we have similar gains for utilizing matrix multiplication for state passing? Also furthermore it seems very viable to use a recursive algorithm for state passing, which would keep the algorithm sub-quadratic. Thanks again for helping me understand this stuff!

**Comment by tridao** [comment]
Yes we tried that. The dimension is usually so small (e.g. 8) that it doesn't matter if we use tensor cores then. That kernel is bounded by memory-bandwidth. As long as you load in the states and write out the states fast, you're good.

**Comment by Hprairie** [comment]
Makes sense, and I appreciate the response!
