### ISSUE TITLE
Assertion error in ssd_minimal

### ISSUE THREAD

**Issue by patronum08** [state-spaces/mamba#456]
Thank you for providing an SSD implemented with PyTorch. However, I noticed that the results of the SSD implemented with PyTorch do not match those of the fused SSD.
![image](https://github.com/state-spaces/mamba/assets/24070800/996ebb3d-084e-496d-a4ea-d58981b8163f)

**Comment by tridao** [comment]
you should try a different value of atol and rtol

**Comment by patronum08** [comment]
![image](https://github.com/state-spaces/mamba/assets/24070800/a9b02e8f-d105-48e6-9ff3-12e63117793e)

I subtracted the two, and the difference between them seems to be not as expected.

**Comment by tridao** [comment]
try (y_min - (y_min / 0.3 * 0.3)) to see what what the typical numerical errors are

**Comment by tridao** [comment]
the numerical errors look fine to me

**Comment by patronum08** [comment]
I understand, thank you for your response.
