### ISSUE TITLE
(about the paper) In the Section5.1, I have a question: Why M matrix, whose element is also matrix, can finally be (T, T) size?

### ISSUE THREAD

**Issue by Nkehougaosuni** [state-spaces/mamba#458]
![image](https://github.com/state-spaces/mamba/assets/124226697/73653090-7f2c-4d3c-99ae-6fb956900f56)

**Comment by albertfgu** [comment]
$M$ is always a $(T, T)$ matrix throughout this paper.

**Comment by Nkehougaosuni** [comment]
这里是张亿锋！您的信件已经收到！

**Comment by Nkehougaosuni** [comment]
Thanks. I understand. Because for a separate SSM, the size of $C_j$ and $B_i$ is $N\times1$, which means here $M_{ji}$ is a scalar.
