### ISSUE TITLE
A mamba scaling problem given the perplexity score curves shown in the TTT paper

### ISSUE THREAD

**Issue by Ava4wonder** [state-spaces/mamba#459]
Hi Dao, mamba is an interesting work! I read the mamba and TTT paper, notice that in TTT paper: https://arxiv.org/pdf/2407.04620v1, Figure 19 shows four plots depicting perplexity trends for different model sizes (125M, 350M, 760M, and 1.3B) as a function of context length. As we could see the perplexity trends for the Mamba and TF pretrain models across these different model sizes: 
- The Mamba model shows a trend of decreasing perplexity with context length up to a certain point (usually around 8k), beyond which perplexity tends to increase slightly or stabilize.
- The TF pretrain model generally shows a trend of decreasing perplexity with increasing context length, with sharper declines at larger context lengths. 

**My question is: How is your opinion about the scaling observations between mamba and TF? With an increasing model size, will mamba shows a trend of decreasing perplexity with increasing context length? Beyond a certain model size, will the mamba perplexity curve match or even outperform TF-pretrain?**

Looking forward to your reply:)

**Comment by tridao** [comment]
We generally use github issues for issues about the code, not for Q&A

**Comment by Ava4wonder** [comment]
Sorry for the inappropriate use. May I close this issue and contact you via email instead?
