### ISSUE TITLE
I tried 370M parameters for 4096 context length, memory usage is quite high, ~30GB VRAM

### ISSUE THREAD

**Issue by huseinzol05** [state-spaces/mamba#5]
Thanks for the research and public code, you can check the notebook at https://github.com/mesolitica/malaya/blob/5.1/pretrained-model/mamba/causallm.ipynb,

1. 4096 context length.
2. batch size of 5 only.

before running the notebook,
```
22394MiB / 81920MiB
```

after calculate the loss only using 370M official parameters from HF,
```
52344MiB / 81920MiB
```

**Comment by huseinzol05** [comment]
If this as expected, I am going to try to deepspeed it on multinodes, thanks!

**Comment by tridao** [comment]
What's the memory usage of a transformer of similar size (e.g. pythia 400m)?

**Comment by huseinzol05** [comment]
OOM, I tried https://huggingface.co/EleutherAI/pythia-410m

looks good, thanks!

**Comment by Excutioner** [comment]
> OOM, I tried https://huggingface.co/EleutherAI/pythia-410m
> 
> looks good, thanks!
you mean pythia use more memory than mamba at the same size?

**Comment by Excutioner** [comment]
> OOM, I tried https://huggingface.co/EleutherAI/pythia-410m
> 
> looks good, thanks!

you mean pythia use more memory than mamba at the same size?
could you please tell me about the memory usage of pythia?thanks a lot
