### ISSUE TITLE
causal_conv1d import error

### ISSUE THREAD

**Issue by ftgreat** [state-spaces/mamba#50]
After installation from wheel (causal_conv1d-1.0.2+cu122torch2.1cxx11abiTRUE-cp310-cp310-linux_x86_64.whl), errors happened in importing causal_conv1d. 

Is there any mismatch in versions of cuda and torch? Thanks for your advice.

![image](https://github.com/state-spaces/mamba/assets/10432020/b9061b88-cc4b-4c60-864a-5b8700dd3680)

torch.__version__: '2.1.0a0+4136153'
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

**Comment by habbler** [comment]
Make sure you install causal-conv1d<=1.0.2
That fixed it for me.

**Comment by ftgreat** [comment]
> installated from wheel (causal_conv1d-1.0.2+cu122torch2.1cxx11abiTRUE-cp310-cp310-linux_x86_64.whl).

causal-conv1d==1.0.2

**Comment by ftgreat** [comment]
My docker is based on nv-ngc-2306. 
Trying switch into another docker following https://github.com/state-spaces/mamba/issues/9.

**Comment by ftgreat** [comment]
> My docker is based on nv-ngc-2306. Trying switch into another docker following #9.

Following this issue and switch the docker, installation is ok. 

export MAMBA_FORCE_BUILD=TRUE; pip install .
