### ISSUE TITLE
Curious about native ddA cumsum?

### ISSUE THREAD

**Issue by Hprairie** [state-spaces/mamba#502]
I have been thoroughly enjoying looking through the triton kernels for SSD, and have been programming up my own implementation. While there are a lot of tiny tricks that I am able to parse together from the comments, I am a little lost as to why computing ddA in `_chunk_scan_bwd_dcb` is much slower. Is it just simply register pressure, or something else?

Any intuition on this would be very helpful!

**Comment by tridao** [comment]
I'm guessing register pressure. I didn't investigate too much (e.g. looking at ncu profile).
