### ISSUE TITLE
How to modify mambaV2 to set causal=False?

### ISSUE THREAD

**Issue by deepinact** [state-spaces/mamba#519]
I changed IS_CAUSAL to False, but the model encountered an 'idx_dim >= 0 && idx_dim < index_size && "index out of bounds"' issue.
I tried to rule out other issues, but I still don't know how to fix this bug.
https://github.com/state-spaces/mamba/blob/62db608da60f6fc790b8ed9f4b3225e95ca15fde/mamba_ssm/ops/triton/ssd_chunk_scan.py#L1271

<img width="1103" alt="屏幕截图 2024-08-10 222437" src="https://github.com/user-attachments/assets/a5d5a02e-8201-496d-a641-f7385fd42d3d">

**Comment by Hprairie** [comment]
I will say that the kernel is not set up for Non-Causal computation. I.e if you are looking for something like self-attention or bi-directionality encoding the mambaV2 kernel doesn't really support this. You can check out https://github.com/goombalab/hydra if you are looking for bi-directionality. Hydra doesn't have an optimized kernel, however, I am writing one rn, which I'll link to when I'm done with it.

**Comment by deepinact** [comment]
Thanks, I'll try this.

**Comment by Hprairie** [comment]
For anyone interested, I have the fwd pass implemented and am working on the bwd pass rn. I have created a repo, where I will have the final kernels. A link can be found here: https://github.com/Hprairie/Bi-Mamba2
