### ISSUE TITLE
Reducing _chunk_scan_bwd_kernel computation

### ISSUE THREAD

**Issue by Hprairie** [state-spaces/mamba#520]
Hey I have been reading through the backward triton kernels and I think I found a bug. I could be wrong, but in `_chunk_scan_bwd_kernel`, we don't mask off `tl.exp(dA_cs_m[:, None] - dA_cs_n[None, :])` and thus we will have a small amount of gradient errors. It will be small since tl.exp() should be negative, for out-of-bound areas. Furthermore, aren't we wasting a decent amount of computation in the causal case, as the gradients for the upper triangle for `dCB` should be 0?

**Comment by Hprairie** [comment]
To clarify, I think [ssd_chunk_scan.py:819](https://github.com/state-spaces/mamba/blob/62db608da60f6fc790b8ed9f4b3225e95ca15fde/mamba_ssm/ops/triton/ssd_chunk_scan.py#L819), should be masked before multiplying with dCB. Furthermore, since this is true we should only run kernels that work on values on the lower triangle.

**Comment by Hprairie** [comment]
Whoops, I complete missed line [844](https://github.com/state-spaces/mamba/blob/62db608da60f6fc790b8ed9f4b3225e95ca15fde/mamba_ssm/ops/triton/ssd_chunk_scan.py#L844). However, I still notice that we are doing a significant amount of extra computation, especially if we have a large chunk_size. Thus shouldn't we specify the kernel to only run on the lower triangle?

**Comment by Hprairie** [comment]
I again missed line [799](https://github.com/state-spaces/mamba/blob/62db608da60f6fc790b8ed9f4b3225e95ca15fde/mamba_ssm/ops/triton/ssd_chunk_scan.py#L799), which answers my question.

**Comment by tridao** [comment]
glad you figured it out :D
