### ISSUE TITLE
ERROR: Failed building wheel for mamba-ssm

### ISSUE THREAD

**Issue by yojeep** [state-spaces/mamba#534]
Building wheels for collected packages: mamba-ssm
  Building wheel for mamba-ssm (setup.py) ... error
  error: subprocess-exited-with-error
  
  ?python setup.py bdist_wheel did not run successfully.
  \u2502 exit code: 1
  \u2570\u2500> [8 lines of output]
      
      
      torch.__version__  = 2.4.0+cu121

**Comment by wzy1845** [comment]
hi I also encountered the same problem. How did you solve it in the end? thank!

**Comment by yojeep** [comment]
> hi I also encountered the same problem. How did you solve it in the end? thank!

I can't access github directly with pip  in China,  you can download the .whl file according to the link provided by pip manually
