### ISSUE TITLE
Possible bug in computation of chunk_scan and chunk_state

### ISSUE THREAD

**Issue by vidavakil** [state-spaces/mamba#551]
https://github.com/state-spaces/mamba/blob/62db608da60f6fc790b8ed9f4b3225e95ca15fde/mamba_ssm/ops/triton/ssd_chunk_scan.py#L1818

Also at:
https://github.com/state-spaces/mamba/blob/62db608da60f6fc790b8ed9f4b3225e95ca15fde/mamba_ssm/ops/triton/ssd_chunk_state.py#L988

Hello,
I believe in the above two lines of code in chunk_scan_ref() and chunk_state_ref(), dt should not be used, because dA_cumsum has already consumed and accumulated any required dt (https://github.com/state-spaces/mamba/blob/62db608da60f6fc790b8ed9f4b3225e95ca15fde/mamba_ssm/ops/triton/ssd_combined.py#L645). If this is indeed a bug and the triton implementations also use this extraneous dt, then they need to be fixed too.

**Comment by PeaBrane** [comment]
I'm not the author so I may be wrong. But I think the extra `dt` (or Delta) is due to the ZOH discretization. e.g. page 4 of the [s4d paper](https://arxiv.org/pdf/2206.11893). Maybe someone can confirm.

**Comment by PeaBrane** [comment]
Yes, because dt is multiple by B to get `B_hat`, hence where the additional dt comes from I think

**Comment by vidavakil** [comment]
I see, you are right. I had missed that part. Thank you!
I'll close the issue.
