### ISSUE TITLE
how to use MAMBA with dynamic delta t

### ISSUE THREAD

**Issue by peterphancong** [state-spaces/mamba#603]
Hi authors,

Thank you for your great works. I would like to have a question about the dynamic delta_t
In your paper, I found that MAMBA overcome the issue of time-invariant. As my understand, this indicate the situation where the difference between 2 time points can be varied.
I have a time series dataset with the distance between any pair of timepoints are totally different. 
For example, the time points are 10:00:00, 10:00:20, 10:05:00, 10:07:01, .etc.
At each time point, there are many more data fields (other variables).
I wonder how can I input my data into MAMBA to train and use the model to predict the next sequence of data based on input time points

Thank you and hope to receive your help!

**Comment by AlwaysFHao** [comment]
Hello, if my understanding is correct, you want to incorporate time information into d_t, but unfortunately, the d_t generation for Mamba and Mamba2 does not come from timestamps. Our work is aimed at improving this issue. If you are interested, you can learn about our work: https://arxiv.org/abs/2409.16182v2 .

**Comment by peterphancong** [comment]
Thank you for your answer.
That is exactly what I want to ask.
