### ISSUE TITLE
Releasing Transformer++ models

### ISSUE THREAD

**Issue by normster** [state-spaces/mamba#63]
Great work! Would it be possible to release your Transformer++ baseline models (specifically the ones trained on the Pile)?

**Comment by tridao** [comment]
For the scaling law experiments the largest model is just 1.3B trained to 26B tokens (Chinchilla optimal, 20 tokens per param). That's a pretty weak model in absolute term.
Pythia is trained to 300B tokens, so would be much stronger in terms of downstream evaluation.

**Comment by normster** [comment]
Ah, I didn't realize the released Mamba models are different from the scaling law experiments. Thanks for the clarification!
