### ISSUE TITLE
error in backward of inplace operation

### ISSUE THREAD

**Issue by kanyu369** [state-spaces/mamba#638]
When I use mamba2 to build a U-Net, I encounter this error during the backward propagation process when training (it occurs during the second batch):

  RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [768, 4]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

The error occurs at 837 row in the file mamba/mamba_ssm/ops/triton/ssd_combined.py:

    zxbcdt, conv1d_weight, conv1d_bias, out, A, D, dt_bias, initial_states, seq_idx, rmsnorm_weight, rstd, outproj_weight, outproj_bias = ctx.saved_tensors

From the tensor.shape, it can be judged that the problematic tensors are conv1d_weight or conv1d_bias. Does anyone know what to do?

config:
mamba 2.2.0
casua_conv_1d 1.4.0
torch 2.1.1
cuda 11.8
python 3.10

**Comment by sunpihai-up** [comment]
Do you slove this problem? I have a similar issue.
