### ISSUE TITLE
Need some help for model flow

### ISSUE THREAD

**Issue by gymeee0715** [state-spaces/mamba#64]
After the model encode prompt in Mamba, will the model go through the model when generating the next token? I have print("MixerModel") in MixerModel.forward, why I don't see print result on the
```
 for decoding_seqlen in decoding_seqlens:
        if (batch_size, decoding_seqlen) not in cache.callables:
            cache.callables[batch_size, decoding_seqlen] = capture_graph(
                model,
                cache.inference_params,
                batch_size,
                max_seqlen,
                decoding_seqlen=decoding_seqlen,
                mempool=cache.mempool,
                n_warmups=n_warmups,
            )
```

**Comment by albertfgu** [comment]
1. The model goes through the `step` function, not `forward` during the decoding process
2. The computation graph is cached to avoid Python overhead, and it will not actually call the python function repeatedly. So the print statement will probably trigger once but then not print repeatedly during decoding

**Comment by tridao** [comment]
You can pass in `cg=False` to the `generate` function to disable the graph, so things will print out.
