### ISSUE TITLE
Low training efficiency with large batch size and short sequence length

### ISSUE THREAD

**Issue by bsxxdw** [state-spaces/mamba#69]
Hi, congratulations for your awesome work!
I am running some tests on mamba and I find a weird phenomenon:
Consider two hidden states with shape [bs, seqlen, dim] and [bs * 32, seqlen // 32, dim], the forward and backward speed with the former input is much faster than the latter (both hidden states should share the same flops). Is this normal?

**Comment by tridao** [comment]
I don't think the speed should be that different, unless seqlen // 32 is very short.
We tried training with (bs=16, seqlen=2k) takes the same time as (bs=4, seqlen=8k).

**Comment by bsxxdw** [comment]
Wow, thanks for your so fast reply.
For my case, seqlen is set to 256, so the second hidden state only has a sequence length of 16.
Is this due to the parallel scan algorithm?

**Comment by tridao** [comment]
Yeah seqlen=8 is too short, we allocate 32-128 threads to process per sequence so anything shorter than 128 is not using the GPU resources effectively.

**Comment by bsxxdw** [comment]
Thank you ❤️
