### ISSUE TITLE
How to pass attention mask?

### ISSUE THREAD

**Issue by thistleknot** [state-spaces/mamba#76]
How am I supposed to train on response if I can't pass a mask.

**Comment by pjsample** [comment]
Yeesh, apparently the authors are wrong and this is a transformer model. RIP authors.

**Comment by thistleknot** [comment]
Apparently I'm on an older build
https://github.com/state-spaces/mamba/pull/70/commits/9f75b2bb500c462875d2c51ea8b7998f37b8e49b
