### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by bsxxdw** [state-spaces/mamba#81]
Hello authors!

While training Mamba on ImageNet1K (using a 224 image size, 16 patch size, and 196 sequence length per image), I've encountered instability issues. After running for several epochs, a segmentation fault occurs, interrupting the training process. This error seems to occur randomly. Have you experienced a similar issue, or do you have any suggestions for resolving this problem?

Thank you in advance for your assistance. I eagerly await your reply.

**Comment by tridao** [comment]
No I've never seen segmentation fault. Could also be hardware issues.
