### ISSUE TITLE
Is it running autoregressively?

### ISSUE THREAD

**Issue by forresti** [state-spaces/mamba#82]
The code seems to be working properly, but I have a question about how it works. I run this:
`python benchmarks/benchmark_generation_mamba_simple.py --model-name "state-spaces/mamba-2.8b" --prompt "The climate of Tokyo is" --topp 0.9 --temperature 0.7 --repetition-penalty 1.2`

And it produces 100 tokens, which decode to `The climate of Tokyo is very hot and humid, with an average temperature in January being around. The city's annual rainfall averages, but can reach as high  in the summer.\n\nHistory \n was founded on April 1st 1871 by a group led mainly from Kōshū (now part of Shizuoka Prefecture) who were dissatisfied that their local government had been taken over after it became independent following its secession during Meiji Restoration; they wanted to create another prefectural capital for`.

I modified benchmark_generation_mamba_simple.py to just call `fn()` once instead of `repeats+1` times.

I was curious how many times it calls the forward() pass for one Mamba layer. So, I made this small code change:
```
class Mamba(nn.Module):
  ...
def forward(self, hidden_states, inference_params=None):
  ...
  if self.layer_idx == 0: print("Mamba: calling forward on layer 0")
```

I thought I would see `Mamba: calling forward on layer 0` print 100 times, since it  produces 100 new tokens. But, what surprised me is that it only prints `Mamba: calling forward on layer 0` 4 times.

What I am wondering is, shouldn't it call the layer once per token? Or... how does the autoregressive inference work for this particular model?

**Comment by tridao** [comment]
We cache the computation graph so not all the prints will show up. You can set `cg=False` in `generate` to disable this caching, and all the prints should show up.

**Comment by forresti** [comment]
Thank you for the fast and detailed response! That worked! With `cg=False`, I see 100 model executions to generate 100 tokens.
