### ISSUE TITLE
Direct Throughput Comparison to RetNet ? 

### ISSUE THREAD

**Issue by ahatamiz** [state-spaces/mamba#91]
Congratulations for such a nice work ! are there any benchmarks for direction comparison to RetNet in terms of throughput (or latency) ? Figure 4 in the paper is the only comparison to RetNet, among other models in terms of FLOPs.

**Comment by tridao** [comment]
No we mostly compared with Transformers.

**Comment by ahatamiz** [comment]
I see. The results seems incredible for comparison to Transformers. Would also be great to know how it compares to RetNet in the future.
