### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by aaaaamilk** [state-spaces/mamba#92]
WARNING:root:CUDA extension for structured kernels (Cauchy and Vandermonde multiplication) not found. Install by going to extensions/kernels/ and running `python setup.py install`, for improved speed and memory efficiency. Note that the kernel changed for state-spaces 4.0 and must be recompiled.

How do I fix the warning above?

**Comment by tridao** [comment]
Are you sure it's from this repo? I did a search for "Cauchy" and found nothing.

**Comment by aaaaamilk** [comment]
Yes, I'm using the code from this repo.

**Comment by nat42** [comment]
Doesn't appear to be from this repo, the message seems to come from some s4 code from here https://github.com/state-spaces/s4/blob/main/models/s4/s4.py

**Comment by BlenderWang9487** [comment]
@aaaaamilk  Hi. I search the log on github and found that this exact same logging code is from another repo of state-spaces: `state-spaces/s4` [here](https://github.com/state-spaces/s4/blob/a246043077dbff8563a6b172426443dced9a9d96/models/s4/s4.py#L52)
Are you sure this warning really from this repo (mamba)?

**Comment by tridao** [comment]
I think the warning is from the s4 repo.
