### ISSUE TITLE
Question about cuda speedup

### ISSUE THREAD

**Issue by hsm1997** [state-spaces/mamba#94]
Hi, I recently looked into your paper and code, and I see descriptions of cuda optimization here:

![截屏2024-01-08 11 23 47](https://github.com/state-spaces/mamba/assets/59716501/6e388531-4a26-4872-a6a4-a32edde95111)

and

![截屏2024-01-08 11 27 26](https://github.com/state-spaces/mamba/assets/59716501/8360ebdd-a5b7-4df6-91f4-398124f6bf49)

My question is, how many of the 20-40x speedup come from memory optimization (O(BLDN) IO to O(BLD) IO with recompute), and how many come come from efficient scan kernel (Ktraits::BlockScanT(smem_scan).InclusiveScan)?

Thanks!

**Comment by albertfgu** [comment]
I'm not sure that it makes sense to disentangle these components. For example, is there an alternative you have in mind that has the memory optimization without the efficient scan kernel?

**Comment by hsm1997** [comment]
thanks for the reply:-)
actually I'm thinking of an alternative that has the efficient scan kernel without memory optimization
