### ISSUE TITLE
Does Mamba use any matrix multiplication?

### ISSUE THREAD

**Issue by hesingh** [state-spaces/mamba#95]
If yes, please point me to relevant code.

**Comment by tridao** [comment]
Yes, there are nn.Linear in `mamba_ssm.modules.mamba_simple.py`.

**Comment by hesingh** [comment]
Thanks much. I am looking at hardware for both mamba and Transforner. Did you see this research?
https://hanlab.mit.edu/projects/hat

When you get a chance, please add a doc dir to the repo.
