### ISSUE TITLE
Mamba is deeper but narrower than typical models of the same size

### ISSUE THREAD

**Issue by kmn1024** [state-spaces/mamba#96]
Looking at the 3B (2.8B) models, Mamba has 64 layers, whereas GPT-Neo, OPT, and RWKV only have 32.

Is model depth a confounding factor to Mamba's amazing performance? Are there checkpoints available for a Mamba 3B with 32 layers but twice the hidden-dim?

**Comment by tridao** [comment]
As mentioned in the README
```
The layer count of Mamba doubles that of a Transformer with similar size, as two Mamba blocks are needed for each "layer" (MHA block + MLP block) of a Transformer.
```

**Comment by kmn1024** [comment]
Ah, sorry I missed that!
