### ISSUE TITLE
Packaging module missing when installing

### ISSUE THREAD

**Issue by dieki-n** [state-spaces/mamba#98]
When I try to install mamba I get a "no module named packaging" error. This happens both when trying to install from the repository, and when building from source.
```
(.venv) PS \mamba> pip install .      

        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'packaging'

```
But packaging is installed:

```
(.venv) PS \mamba> pip install packaging
Requirement already satisfied: packaging in \.venv\lib\site-packages (23.2)
```

Full output: https://pastebin.com/HmQMzXLv

**Comment by dieki-n** [comment]
Resolved issue by install wheel:

`pip install wheel`

It now installs without issue.

**Comment by benlin1211** [comment]
I resolve this issue by installing `packaging` directly.

```
pip install packaging
```

**Comment by TinChung41** [comment]
> Resolved issue by install wheel:
> 
> `pip install wheel`
> 
> It now installs without issue.

this work  for me when using older version of mamba: `mamba-ssm==1.2.0.post1`
